#+TITLE: English
#+AUTHOR: Gu Feng
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/code-hover.css" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/org.css" />
#+HTML_HEAD: <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

* Godzilla
+ The Godzilla is no longer =terrestrial=, it's =airborne=.
+ This is our =needle in the haystack=, but it is =imperative= that we find it.
+ Welcome, glad to =have you on board=.
+ =My condolences=, I'm really sorry for your loss. I sent him =a letter of condolences=.
+ =Parasitic spores=, one =dormant=, but the other =hatched=. =Catalyzed= by a mining company =unknowingly drilled into its tomb=.
+ =The hatchling burrowed straight for= the nearest source of radiation, =the power plant=, and =cocooned= there for 15 years, absorbing its =radioactive fuel= to =gestate=, to grow.
+ The creature have electrical effect on everything =within a close proximity=.
+ Anything =at all= would help us.
+ Where is it =headed= now? / I'm =headed= to Hawaii.
+ For the =comfort= of others. / For others' =sake=.
+ We've just received =an intel report= from the intelligence.
+ The ship appears at 50 =nautical miles= northwest.
+ Some ship is asking for help, we are =picking up a distress= signal.
+ They =are headed= to the beacon.
+ The =chameleon= survives by =blending in with= its background. / =Chameleons camouflage= themselves =in a variety of= different ways. / Chameleon's =disguise(camouflage)= is like magic.
+ Look, I've got a =ping=. Never mind, it's probably just a =glitch=. I got a =reading= again, it's =right up ahead=.
+ This is a direct command from the =General quarters=.
+ The plane is landing, I'm going up to the =flight deck=.
+ We are =circling= the target. Stand by, got a =visual=.
+ AIDS is a universal bogey.
+ Run! =Tsunami=!
+ There was another spore, =intact=. But we =vivisected= it and it was =disposed of=. / This is the safest =means of disposing of nuclear waste=.
+ They are =converging= here, we just wait for them.
+ Regular bomb can't kill them, we can =rig a nuclear warhead with a shield timer=.
+ The radiation =lures= MUTOs.
+ We =detonate= the bomb in desert, with minimal =fallout risk to= the city.
+ You can't be serious, they =feed on= radiation.
+ If you have any other ideas, =I'm all ears=.
+ My first =priority= is to =safeguard= our citizens.
+ The watch is =stopped=.
+ Everybody =disembarked=! / Soldiers, =dismiss=!
+ A possible hurricane is approaching, locals are =being urged to please find shelter=, =stay indoors= and =stay off= the road.
+ After the explosion, there are =debris= everywhere.  / Many people close to the blast were killed by the =shrapnel= of the bomb.
+ This bomb makes the old one look like a =firecracker=. Nothing can =withstand that blast=.
+ Many Americans think their legal system has =gone haywire(chaotic, disordered, out of order)=.
+ This suit is obviously too fashionable for him, he is really an =old school=.
+ You can always make the old watch work. =Take a licking, keep on ticking=.
+ We must hurry, it has =outrun= us.
+ This is a direct order from the =tactical operations command=.
+ I =retrofitted= that device myself.
+ =With all due respect=, may I ask what's the second plan?
+ Two man tied the boat =to the pier= at both =stem= and =stern=. / They went for a =stroll= along the =waterfront=. / The ferry attempted to =dock on= the island. / The =harbor= admits large =tankers and freighters=.
+ If the MUTOs have =spawned=, they will be building a nest.
+ When you find the warhead, how long can you =disarm= it?
+ They have all been =briefed=, you will be on your own, we have no =extraction= plan. 
+ I'll do =whatever it takes= to save her. / We must drive out the enemy =at all costs=.
+ The monster is an =alpha predator=.
+ We haven't lost yet, we still =have a chance=. / I thought I might =have a shot=.
+ The =arrogance= of man is thinking that nature is in our control and =not the other way around=.
+ We are still trying to open it, but it's not =budging=, it's =sealed shut=.
+ Find the =ignition= and start this boat.

* LTT1 Lesson1-3
+ NAmE'vest BrE'=waistcoat= / NAmE closet BrE =cupboard= / NAmE'sink BrE'=washbasin= / NAmE'apartment BrE'=flat= / NAmE'rinse BrE'=swill= / At least =rinse= your mouth.
+ =So off they went=, headed to the next destination.
+ He saw me at a distance and =came up to= me immediately. / The name =came up= a lot in the discussion. / New year is =coming up= soon. / Call me if anything =comes up=. / The house =comes up= for sale. / New jobs will =come up= soon. / He always =comes up with= new ideas. / I don't think he can =come up with= any money.
+ What happened to him? He is =looking upset=. / You are =looking good= in this dress. / Do I know him? He =looks familiar=.
+ The table is covered with =a piece cloth=. / I need to change my =clothes=. / What is your favorite =item of clothing=?
+ I spilled the water. BrE'=spilt= / Tonnes of oil =spilled from= the tank. / The words =spilled out in a rush=. / Some jobs are likely to have a negative =spillover into= family life. / The drug has unknown =side effect=. / This article has =negative impact= on readers.
+ My wife is =laundering clothes= in the =launderette (laundrette, NAmE'laundromat)= at the street corner. / It's illegal to =launder ill-gotten= money. / My clothes are all dirty, I'm going to =do my laundry=.
+ It's none of their business, they are just =outsiders from off the street=.
+ He wanted me to jump, I'd rather not.
+ I've got a headache, I need some =aspirins=.
+ I like =suspense= movies, especially =Hitchcock's=!
+ I have to go to work now, but I can't find my =overall=.
+ They should start saving their =pocket money=, I'll create a =savings account= for them. / During holiday, most students will =take part time jobs= to make some =spending money=.

* NCE2 Unit1
+ His private life =came under media scrutiny=. / All citizens in the nation =are subject to= the law. / Governments must be =open to public scrutiny=.
+ She spent a lot of money on the crap, so I got =very angry= with her.
+ I =turned round(around)= and looked at them angrily, but they did not =pay any attention=.
+ I never =get up early on= Sundays. I sometimes =stay in bed= until lunchtime.
+ Just then, the telephone =rang=.
+ You can't give them everything they want, you =spoil= them!
+ I visited =museums= and =sat in= public gardens.
+ He =taught me a few words= of Italian.
+ I’ve never been =abroad= before.
+ =In a way(in some way, in one way)=, television is more =challenging= than theater.
+ The chair is =in the way=, move it!
+ I =ran into= them on the way home. / The bank =ran into= financial difficulties. / Our debts are =running into= millions of dollars.
+ He's the man who =goes through= his whole life =blending into the wallpaper=, =seemingly content= to work hard =day-in and day-out= and =leave the spotlight to others=.
+ He has sent =a great many requests for= spare parts. / Can you =spare= me a moment?
+ They went =on a short excursion= into the forest. / Seems she has gone on =an excursion= into non-related topics.
+ =Up to now(up till now)=, I haven't been abroad even once.
+ The beggar =stood on= his head and sang songs.
+ He =calls at= every house once a month. / I’ll =call for= you(pick you up) tomorrow 8 pm.
+ Bags have difference size. =Knapsacks= are big, =backpacks= medium and =shoulder bags= are usually small.
+ The robbers =rushed out= of the bank and =took off= in their car. / =Take off= your shoes! / The new magazine has soon =taken off= (become very popular). / The plane accelerated down the runway for =take-off=. / The film is a =take-off= (copying) of Star Wars.
+ They usually =knock off= (get off work) around five to drink beer. / I =knocked= the lamp off the table. / The shop assistant =knocked= 10% off the bill.
+ Try not to =knock= that vase over.
+ The blows =knocked me out= (stunned me).
+ a =bag= of flour / a =bar= of soap / a =tube= of toothpaste / a =flowerpots= with plastic plants / two tall, shapely brass candlesticks
+ the customs house / customs invoice / the level of =customs duties= (tariff) on imports / a customs officer / Arriving =refugees= were =whisked= through customs.
+ Two detectives were =keeping guard= at the door.
+ =To their surprise=, the parcel was full of stones and sand!
+ =Just as= they were chatting, the boss entered.
+ Everybody in the town =enters for= the competition each year. / He will be =taking part in= an important race.
+ He has built a =neat= path and a wooden bridge =over= a pool.
+ I always win a little =prize= for the worst garden in the town.
+ What does the phrase =refer to=?
+ a large =crowd= of people
+ The minute/hour/second =hand= did not move.
+ The spoon is =made of= silver / Glass is =made from= sand and lime. / This is one of those applications that PDAs were =made for=. / You two are just =made for= each other.
+ He came to me and =whined about= his trouble for hours. He is really a =whiny= man. / People get rude and whiny when they are exhausted.
+ "One good turn deserves another."
+ He has a interesting job and also get a good salary.
+ I will =pay you back (repay you)= (pay it back to you) soon.
+ The captain will =sail from= Portsmouth to France tomorrow.
+ It’s =up to you= to make the final decision. / I don’t think he is =up to= the job. / The total number is =up to= 3 million. / I can take =up to= four people in my car. / up to now (up to this time) / What have you been =up to= recently? / You think your idea is =up to= mine?
+ This is the =final call for boarding on= (final boarding call of) flight MU 7766. 
+ The police always have =a difficult time= on these occasions, trying to =keep order= of the events.
+ by walk =by walking =on foot =by foot / by bus / by car / by train / by sea / by air
+ I don’t =take= orders. / You are no king to me!
+ Single quotation marks looks like =apostrophes=. / double quotation marks / The article starts with a =quote= from the Bible.
+ He waved to me and asked me for a lift.
+ =Apart from= (Except for) a few words, I don’t know any French at all.
+ You needn’t salute me. / He raises his arms in a triumphant salute. / He nodded a salutation.
+ A financial aid is available.
+ Soldiers =tramping= through the streets. / The =tramp= of marching feet is so loud. / She is a =tramp (whore, prostitute, promiscuous woman)= (slut) who sleeps around. / He is a =tramp (vagrant)= (beggar) off the street. / They start off on a =tramp= (trek) over the mountains.
+ It's a typical hero vs. =villain= movie.
+ Remember me to your parents.
+ The President's envoy =set off on= another diplomatic trip. / They =set off for= (set out to) a remote place. / Their escape =set off= (sound) the alarm. / Who =set off= the fire extinguisher? / Who =set off= the bomb? / The arrival of the charity van =set off a minor riot= as villagers =scrambled for= a share of the aid. / The joke =set him off= laughing. / Blue suits you, =sets off= the color of your hair.
+ I'm innocent, he =set= me =up=! / You =stood me up= (blew me off)!
+ Locals =looked on= (look at it) in surprise as hitch-hikers, cyclists, bikers, cars, vans and minibuses =filled up= the village square.
+ =Pop and folk singers and musicians= all attended the Grammy. / Waiters' job is to =attend to= customers.
+ She seemed =irritable(always loses temper)= (easily made angry), and annoyed with my every move. / Exams make me =nervous=, restless or uneasy.
+ I don't go on a vacation often, I can’t =afford= the time and money.
+ This note is only a =reminder=. / She gulped down the =remainder= of her coffee.
+ Just =let it go= (stop thinking about it all the time). / =Let it go of me= (Let me go)!
+ Despite of their appearances, traffic police are sometimes very polite.
+ I don't love you =in spite of= that, I loved you because of that.
+ He is a millionaire and he never wears =ready-made= suites. / Coco Channel was oringinally a =milliner=.
+ I can’t pay the bill, I =haven’t got= (have lost) my bag.
+ =Give in= your exercise book. / He can hardly bear it anymore, he will soon =give in, give up, ,surrender= / You have to =give up= (quit) smoking.
+ A sign with =an exclamation mark= on it means warning.
+ The play may begin =at any moment now= (real soon). / "We’ve sold out," the girl said. "What a pity!" Susan =exclaimed=.
+ I =might as well= have them, as I don't have other choice.
+ She took care of her =bed-ridden= grandma for years. / The refugees lived in =disease-ridden= environment.
+ He suffered =considerable= pain. / He suffered from a painful and =lingering= death.
+ She wanted to play the =martyr to= the society. / She was =martyred= for her faith.
+ This does not =worry= me anymore.
+ I was totally confused back then, but the professor =set me straight=.
+ I’m even less lucky.
+ Aeroplanes are slowly =driving me mad=.
+ It is not used before. Last year, however, it =came into use=.
+ People have been driven away from their homes, but I’m =determined= to stay. / He drives his car very badly. / Our army drove the enemy back.
+ Both girls write to each other regularly now.
+ He congratulated me =on= having got engaged.
+ Did anything emerge =from= your discussion?
+ I dreamt =of= you last night.
+ You can never rely =on= him to be punctual(on time). / He is a *liar*, he is not =trustworthy=. / I suppose I can =count on= you for help =in(with)= this matter. / You can depend =on= me.
+ I insist on you telling me the truth.
+ They can only cure him =of= his illness if they operate =on= him.
+ I haven't accused him =of= anything, but I suspect him =of= having taking it.
+ We expect a great deal =of(with)= you.
+ My hands smell =of= soap.
+ We have embarked =on= a new scheme.
+ I believe in taking my time.
+ She prides herself =on= her clean house.
+ We must =economize on= fuel. / Cycling is more =economical= than driving. / She lives a =frugal= lift. / Backbone members are more likely to survive a =stuff cutback=. / The government's deficit is so high that we need a =cutback in public spending=. / Customers are =drawing(pulling) in their horns= at a time of high interest rates. / Cuts in defense spending forced the aerospace industry to =retrench=. / He needs to =scrimp and save (tighten his belt)= while looking for a job. / =Scrimping on= safety measures can be a false =economy=. / Many families must =skimp on= their food and other necessities just to =meet= the monthly rent. / He never =stint on= wining and dining. / To avoid having to =stint= yourself, =budget= in advance. / His boss is =stingy= and idle.
+ He =undertook= that challenging job. / My left knee is very =susceptible to= injury (*injury-prone*). / My jacket is water =proof=./ She is =apt to= (often) talk loudly. / Such thing is really =liable to= (likely to) happen.
+ Economy is often =subject to= politics. / The man =subjected= her wife =to= four years of *beatings and abuse*.
+ He headed south after a =stint= in that village.
+ The administrator is =holding back= (waiting) for several reasons.
+ He doesn't have a job, he lives =on= his mother.
+ He was employed =in= that factory.
+ I can assure you =of= my support.
+ Do you approve =of= hunting.
+ I despair =of= ever loving him! / Being desperate is the feeling of =despair= and =inadequacy=. / She wrote to him in =desperation= before the suicide.
+ He delights =in= annoying me.
+ She is really pessimistic and always =pours(throws) cold water (put a damper) on= our ideas.
+ He felt very upset and started to complain about this wicked world, but was interrupted by a knock =at= the door.

* NCE2 Unit2
+ '' and "" are speech marks.
+ The boys =put up= their tent. / I'm too tired to =put up with(endure, tolerate)= any nonsense. / The shop decided to =put up= prices. / put up a poster, a sign or a notice / I will put up(invest in) all my money for the new project. / You needn't leave tonight, we can =put you up= in the spare room.
+ They =put off= (postpone) the meeting tomorrow. / The accident =put him off= driving.
+ His =evasive= reply =prompted= me to ask another question.
+ He believes in ancient myths.
+ But ever since he moved in, he has had trouble =with the neighbors=.
+ The most surprising thing about it, however, is that it can land on a =ploughed= field. / He was most surprised.
+ Old houses here have been rebuilt to =a block of flats=.
+ BrE'=carpark= NAmE'parking =lot=
+ refuse a =request= / deny an =accusation=
+ Come and sit next to me! / Sit by me!
+ The river cuts across the park.
+ They cooked a meal =over= an open fire and told stories =by= the campfire.
+ The food =smelled= good!
+ They =put out= the fire and =crept= into their tent.
+ Their sleeping bags were warm and comfortable, so they all slept =soundly=. But some time later, they all =leapt out= of their sleeping bags and hurried outside.
+ The stream =wound= its way across the field and =flowed= right under their tent.
+ There were some people =rowing on= the river.
+ They =called out= to the man but he did not hear them.
+ I turned round to look at the children, but there weren't any =in sight= (out of sight).
+ It can get very =rough= in the Mediterranean. / Many great cities are built on rivers. Paris is on =the Seine=, London is on =the Thames= and Rome is on =the Tiber=.
+ The fishermen seine salmon in a big seine boat.
+ Trekking expedition to Antarctica is impossible. / the Arctic
+ neutral and non-aligned European nations / The bombs were neutralized. =disarmed / Chemical splashes on skin should be neutralized immediately. / Neutralizing individuals is an euphemistic saying of killing people. / During the war, Switzerland maintained its neutrality. / The terrorists are demanding a large payment in exchange for the neutralization of the bombs.
+ The US said it would denuclearize most of its naval vessels. / My wife and I have been working together for the cause of peace, demilitarisation and denuclearisation.
+ The rebels have set up a de facto administration.
+ Frank was the head of a very large business company.
+ He bought a small shop of his own. / In his twenties, he used to make spare parts for aeroplanes.
+ the hard early years and the long road to success
+ Frank was telling me about his experiences. / This job requires a lot of experience. / He is an experienced worker.
+ People are not so honest as they once were. The temptation to steal is greater then ever before.
+ The woman first bought a few small articles.
+ She handed it to an assistant who wrapped it up for her as quickly as possible.
+ BrE'=full stop= NAmE'period
+ abbreviations:
  Rd.=road St.=street Ave.=avenue Sq.=square Pl.=place Lane Drive
  Mon. Tue. Wed. Thu. Fri. Sat. Sun.
  Jan. Feb. Mar. Apr. May June July Aug. Sep. Oct. Nov. Dec.
+ He was in considerable pain during his performance.
+ The battery is wearing out. / The contraceptive effect will wear off in two days. / As the days wore on, he began to slowly give up hope. / Days of hard work wore him out. / The stair carpet was wore out.
+ A mother who already has non-identical twins is more likely to conceive another set of twins. / About one in six couples has difficult conceiving. / I just can't even conceive of that quality of money. =imagine / She had conceived the idea of a series of novels.
+ We are still in the phase of conceptive design.
+ He put off telling his father the result, hoping to catch him in a good mood.
+ Towards evening, she set out from the coast.
+ She covered a distance of eight miles.
+ On arriving at the shore...
+ The next day we went sightseeing.
+ call at =visit/ call on =drop by / call for / call off / call out to / call sb. up
+ a short while ago
+ He was driving along Catford street.
+ He drove the bus straight at the thieves. / He drove his bus into the back of the battered car.
+ shortly afterwards...
+ He saw two thieves rush out of a shop and run towards a waiting car.
+ He got such a fright.
+ Do not talk to people of this sort.
+ We do not always write the names of areas or postal districts in full when writing the address on letters.
+ Mark arrived back at his office to tie up any loose ends. / You seem at a loose end, aren't you? Come and help me! [NAmE]at loose ends
+ How to give a polite refusal?
+ lenient < tolerant < forbearing < indulgent
+ Being frugal is the opposite of being extravagant.
+ She is restricted from going out with him by her strict father. / She is restricted to staying at home. / She is prohibited from going out. / She was forbidden from seeing him again.
+ When was the last time this country hosted the Olympic Games?
+ A great many people will be visiting the country.
+ an immense stadium / fantastic modern buildings
+ I'm really looking forward to this.
+ look up the word in a dictionary / Don't forget to look me up when you return.
+ The past tense of dream can be either dreamed or dreamt in BrE, but dreamed only in NAmE.
+ Verbs have different forms, ie, past tense, participle and past participle. =id est =namely
+ He planned to settle down in the country.
+ He had no sooner returned than he bought a house and went to live there. / He had hardly had time to settle down when he sold the house and left the country.
+ It will rain continually during the rainy season. =at frequent intervals / It has rained continuously for three days! =incessantly
+ fruits in season / The female is in season.
+ He got a shock and acted as if he had never lived in England before.
+ It was more than he could bear.
+ The dream he had had for so many years ended there.
+ He had thought of everything except the weather.
+ Intel is such an august company. =dignified
+ the next day / the following day / a day later
+ bedside telephone / BrE'bedside table NAmE'=bedstand(night table)= / bedside manner / She kept vigil at the bedside of her critically ill son.
+ Mourners are to stage a candlelit vigil at the People's Square.
+ He telephoned the hospital exchange and ask for a doctor.
+ He said he was inquiring about a certain patient, a Mr. John Gilbert.
+ whether(if) it had been successful
+ He would have to stay for another two weeks.
+ host / hostess / landlord /landlady
+ What's your opinion of the situation in Algeria. =what do you think
+ I took my seat beside her.
+ Her eyes were fixed on the plate and in a short time, she was busy eating, when I tried to make conversation.
+ Will you be seeing it?
+ in despair... / despair of sth.(doing sth.)
+ She went upstairs to make the beds. / He hasn't made much progress. / Make up your mind!
+ The shop does very good business.
+ Do you call that a hat? / I find it beautiful.
+ I needn't be so rude about it. / You needn't have said that.
+ You should look yourself in a mirror.
+ "We mustn't buy things we don't need," I remarked. =observed
+ Did you notice how she was dressed? =what she was wearing
+ after a time =after a while
+ In time, we shall win. =eventually =at last / He came in time.
+ snake charmer
+ We went to have look at him.
+ He began to play a tune. / Sing a song in front of others and be completely in tune. / I tried to be in tune with him.
+ The snake rose out of the basket and began to follow the movements of the pipe. We were very much surprised.
+ It obviously could not tell the difference Indian music and jazz.
+ They took a great many photographs of the mountains that lay below, but they soon ran into serious trouble. At one point, it seemed certain that their plane would crash.
+ They threw out two heavy food bags, so that the plane could clear the mountain by 400 feet.
+ Billy is not home at present. / To be honest, I'm not expecting your presence. / At any rate you will hear it on the radio. =no matter what / He behaves very strangely at times. / He is very pleasant person at heart. / I'm completely at a loss. =don't know what to do / You need to explain it at length. / Under(in) that circumstances you need to use anything at hand.
+ They rushed up to her.
+ In the struggle, the strap broke and, with the bag in their possession, both men started running through the trees.
+ She ran after them, but was soon out of breath.
+ She caught up with them when they were going through the contents of the bag.
+ The strap needs mending.
+ Mr. James Thompson =James Thompson Esq. =Esquire
+ Workers began to unload a number of wooden boxes.
+ No one could account for the fact that one of them was extremely heavy. / How do you account for the company's alarming high staff turnover. / The local officer must account for the accident.
+ I suddenly occurred to one of the workers to open up the box. He was astonished at what he found.
+ on top of a pile of woolen goods
+ He had been confined to the wooden box for over eighteen hours.
+ You see to the luggage, I'll buy the tickets.
+ No one can ask us to submit to unmerited oppression.
+ We have been corresponding with each other for years.
+ Do you object to my smoking?
+ I'm surprised at(by) you.
+ You must reply to this letter.
+ He has some important business to attend to.
+ Do you mean to say you exchange that lovely car for this?
+ Has it occurred to you that she must have arrived at(in) London by now?
+ I was shocked at his indifference.
+ You must comply with the rules of this game.
+ She has so much to cope with.
+ She was quite unprepared for the news.
+ Don't blame me for the accident!
+ I'm disgusted with your behavior. =sick of
+ His debt now amounts to $100.
+ I reasoned with him, but he would not listen to me.
+ She's accustomed to living in comfort. She'll never part with her precious possessions.
+ Please apply to the secretary for information.
+ Just guess at the price of the carpet. =make a guess at / At a guess, 10 right? / It's anyone's guess where it will be.
+ How long have you been working at(on) this exercise.
+ The concert began with a piece by an unknown composer.
+ The house is up for sale.
+ shook his head / nodded his head
+ I'm up for this.
+ My dentist had just pulled out one of my teeth.
+ My mouth was full of cotton wool. / cottons, woolens, silks and linens / Nylons seem more durable than cotton stockings.
+ We searched for the thieves. We kept searching the place until we searched them out.
+ My collection was growing.
+ In answer to these questions, I nodded.

* NCE2 Unit3
+ He saved up for years to buy a real bed with springs and a mattress. / A storm blew up. A gust of wind swept the bed off the roof and sent it crashing into the courtyard below. / Although the bed was smashed to pieces, the man was miraculously unhurt. / He promptly went to sleep again.
+ He didn't have much time to read the newspaper carefully. =He just glanced through(over) it=. / She recognized him =at a glance=. / He suddenly realized it was so late when he =glanced at his watch=.
+	1800 Xizha Rd.,
	Fengxian District,
	Shanghai,
	China.
	14th Sep., 2014
Dear Philip,
Thank you for your letter. I am glad to learn that...
+ If you just keep working without saying anything, =someone else might take credit for your effort=. / The assistance comes with a price. It's not =free aid=, don't =take it for granted=. / I can take you =for a ride= in my new car if you want.
+ "=Get on(off)= the bus!" the bus driver shouted.

* Twitch Malware Spends Users Money
+ The video game streaming site Twitch can spend users' money without authorization.
+ Clicking on the malware links enabled infiltrators to wipe accounts on the gaming shop.
+ The malware woos users with the promise of prizes.
+ The vulnerability originates from an automated account which bombards channels and invites viewers to participate in a weekly raffle for a chance to win virtual items.

* Maleficent
+ Let's tell the story anew.
+ But there was a vast discord between the two kingdoms.
+ a great hero or a terrible villain
+ They had a vain and greedy king to rule them.
+ There are reports of wide spread discontent in the capital.
+ They were envious of the wealth and beauty of Moors.
+ We can take her for a girl. But she is not any girl, she is a fairy!
+ What's all the fuss about?
+ I have never seen a human up close.
+ They meant kill me! / They were to kill me!
+ They are hideous to look at.
+ But we don't kill people for stealing.
+ Come out this instant! =right now
+ Have you fully grown?
+ He casted away his ring.
+ It worth the risk. / It's not worthy.
+ She wandered alone and wondered.
+ He sought to strike it down.
+ No one dare to venture the mysterious Moors.
+ Hidden dangers lurk in every family saloon car.
+ She is just a winged elf!
+ Battalion, attack!
+ when I ascended to the throne...
+ You all swore allegiance to me and to that cause.
+ This will be my legacy.
+ Avenge me!
+ the years faded away
+ She is vanquished?
+ I'm your servant. / At your service.
+ She was christened Susan.
+ We sought to foster peace and good will.
+ I wish you will never be blue.
+ What a glittering assemblage! / a glittering array of celebrities
+ Royalty, nobility, gentry, even the rabble, how quaint.
+ I felt quite distressed.
+ I bear no ill-will.
+ I too shall bestow a gift on the child.
+ She will prick her finger on the spindle of a spinning wheel.
+ She will never awaken.
+ Secretly she entrusted the safety of the child to the magic pixies who would take her to a remote hideaway.
+ She reveled in the sorrow.
+ a snug little cottage
+ It looks dreadful!
+ We just need a proper disguise.
+ We have to blend in.  
+ a chameleon's camouflage
+ gather around
+ You could almost feel sorry for it.
+ They are unequal to the task.
+ She was further consumed by paranoia and vengeance.
+ the fearsome wall of thorns
+ The wolves are dirty and vicious. / It's filthy and stinky.
+ I know you were close by.
+ You mock me!
+ They are fearful of the story.
+ above the cloud and into the headwinds
+ They never faltered.
+ It's the wee hours.
+ I'm such a clumsy fool.
+ I'll best be off then.
+ in this miserable hover =hut =cabin =shack shanty / den / shed
+ I have to live with these two imbeciles. =moron
+ They pulled the guards.
+ You are not doing it properly.
+ I'll not ask for your forgiveness, because what I've done to you is unforgivable.
+ I was so lost in hatred and revenge.
+ The two kingdoms unified as a whole. / They united against the enemy.

* LTT1 Lesson4-10
+ I cycle to work everyday.
+ A fortnight is not very short time.
+ Wednesday / Tuesday / Saturday / Thursday
+ I sold the most and got a good commission. / The Ministry of Agriculture commissioned a study into low-input farming. / You can commission them to do paint something especially for you. / I finally finished the commission. / Travel agents charge 1 percent commission on sterling cheques. / The authorities set up a commission to investigate the murders. / If a person uses a gun in the commission of a crime, then he should be given an additional penalty. / The aircraft carrier has been out of commission ever since the last war.
+ Irish / Welsh / Austria / Yugoslavia / Scotland / Finland / Belgium
+ librarian / stamps / ball-point pens / shampoo
+ My manager is rather a brute! =savage =barbarian
+ I should like to see some dressing gowns and I fancy a red, silk one.
+ He tried to telephone the box office and heard a wrong number tone. / He was fed up when he dialed again and got a busy tone. / He tried again and finally get through.
+ I'd like to reserve two tickets at 4.50 pounds, please.
+ You need to collect the tickets before 3 pm.
+ The number has been engaged for ages! Nobody can be that popular.
+ That's one reason I'm ringing. I need some career advice.
+ I've just been sacked.
+ There are the pips, I need to put in more coins, hang on. / I think it's OK to eat grape pips, but not apple's. / She piped Meryl Streep to the part. / I don't want us to be piped to the post.
+ Why I want leave my present job. / Why I am interested in the new job. / How I intend to get to work. / How long I intend to stay in the job. / Where I went to school. / How much I'm paid in my present job. / How much I expect to be paid in the new job.
+ I could not see a thing!
+ I asked him to take me home. He got very angry and said some very unpleasant things.
+ I'm definitely going to loss some weight.
+ Last week the sun shone and it got quite hot.
+ a bank clerk
+ Is yours sweet, too? No, mine is rather sour.
+ Can I help you? Yes, I want to see some cardigans. What size do you take? About forty(fourteen) inches, I think.
+ I'm afraid I can't sew. / Sow the seed in warm place. =seed the land / The field was sown with maize. / Instead, the session has sowed confusion. / Here is a saw and a hammer.
+ I bought the shoes last year, but they have hole in them now.
+ Do you know what time the milk man calls? Which day do the dustman come? Who is the most dependable newsagent?
+ Occasional selfies are acceptable, I guess.
+ What time shall I come?
+ People sit at home night after night watching their favorite programs.
+ Yours sincerely, D. Renton
+ I'm going to weed the garden before seeding it.
+ Do you like roast chicken?
+ He just wanted to make use of me.
+ How have you spent the day?
+ light, lit, lit
+ I have injured my ankle. I fell off a ladder last night.
+ the man with the walking stick
+ cool drink
+ on the front of fashion magazines / a front-page article in last week's paper
+ I need a duster to clean the blackboard.
+ millionaire
+ I have damaged my wrist, doctor. How did you do that? I fell on it.
+ boiled eggs
+ a blue blouse with a high neck
+ I haven't brought my racket.
+ an invitation to a volleyball match
+ It's very fast, with lots of action. / He did not like his actions questioned. / Two leading law firms are to prepare legal actions against tobacco companies.
+ Could I have five pounds? What for?
+ Perhaps you could let me have the ticket for a bit less? Let's say three pounds?
+ I was fed up and didn't do anything.
+ I can't get up the stairs by myself. It's my back, you see.
+ My Mum lives on the ground floor in another flat.
+ She is seventy-eight next birthday.
+ in the evening / at lunch time / at breakfast time
+ the box at the end of the road
+ I'd like some instant coffee. A large jar, please.
+ I got it in a sale.
+ How long have you been smoking for?
+ That's nothing. I was in the middle of swimming when I saw the shark. I started swimming for the shore, of course.
+ Continental breakfast or American breakfast / a morning newspaper
+ shaddock(pomelo) peels / An orange resembles a grapefruit.
+ There was a light tap at the open door.
+ Should I pour you a cup of coffee straight away?
+ Half way across I realized it was a lot further than I thought. I thought I was going to drown.
+ He assembled a panel of scholars to advise him. / The advisory panel disagreed with the decision. / agree on the opinion
+ They earn their =pocket money= (pin money, allowance) instead of asking their parents for it.
+ We seem to be equally divided, two for and two against.

* LTT1 Lesson11-13
+ I'm not surprised. So would I be.
+ I'm going to do the washing-up. [NAmE]wash the dishes
+ I'd like to withdraw fifty pounds from my deposit account.
+ How would you like the money? In fives, please. / five-pound notes
+ Perhaps you'd like to change your order, sir. The sirloin is very tender.
+ Look what that waiter's gone and done!
+ I'm terribly sorry. Perhaps I could sponge it. Just leave it alone. You will only make it worse.
+ If you would like to have the dress cleaned and send the bill to us, we will be happy to take care of it.
+ This just won't do. / This won't work.
+ The wine's got a most peculiar flavor.
+ The beer is like water, not as strong as it used to be.
+ is not any good / is no good
+ You'd better get on with your homework. / Let's get on to the next topic.
+ a decent job
+ a paradox and a contradiction
+ book a double room with bath from 1st to 14th August inclusive
+ BrE'=rucksack= NAmE'knapsack
+ I've been working on my novel. How far have you got with it?
+ I was queuing for the cinema.
+ a watch that tells you the date and the day
+ Head waiter, I want to have a word with you.
+ Our staff has been kept unusually busy this evening. I'll see to it.
+ This coffee is practically cold.
+ The total number of commuters in rush hours is 1,023,000. Of these, ...
+ She went away for a fortnight.
+ call in / call at / call on / come by / drop by
+ Give us a ring if you see anything suspicious.
+ pour out a drink / pour out my thought
+ All the doors and windows were locked from the inside.
+ There is a pool of water on the floor.
+ a layer of sawdust
+ rye bread / bread rolls / gin and tonics / highball cocktail
+ I don't seem to be very useful, do I? There is always another time.
+ We're not allowed to serve drinks before 12 o'clock midday.
+ This table-cloth is disgrace!
+ I can't quite understand how you managed to get 1 plus 2 plus 3 to add up to 4. / I can't understand how such a mistake could have been made.
+ Without my 10 years life in prison, this movie won't exist. =That experience inspired the film=.
+ I did not only make movies. =I worked in television for a time=.
+ Is she fat? I've never met her in person. =What sort of built is she=? / Look at that body, =he is really well-built=.
+ It doesf sound interesting, don't go anywhere, =I'll come over and look at it=.
+ No need to explain, =I see what you mean=.
+ What does she look like? Is she =slim= or is she rather more =plump=.
+ I think I have written everything down. Is there anything else =at all=.
+ Appearance? Of course =I'd like someone good looking=.
+ Looking for a date? How old do you prefer, I mean =what sort of age= of the guy? =Mid-twenties=, I suppose.
+ Do you know where Bolt comes from? =Jamaica=.

* NCE2 Lesson50-52
+ reward for virtue
+ He decided to go on a diet. He began his diet a week ago.
+ He wrote out a long list of all the foods which were forbidden.
+ Yesterday I paid him a visit. I rang the bell and was not surprised to see that Hugh was still as fat as ever. He led me into his room and hurriedly hid a large parcel under his desk.
+ I asked him what he was doing, =he smiled guiltily=.
+ His diet was so strict that =he had to reward himself occasionally=.
+ I don't need a clock in the morning. =I always rise at six o'clock=.
+ After the concert, =everybody rose and clapped=.
+ If the problem =arise= again, we still need to deal with it.
+ The sun has just =risen or set=. / Sunrise at =dawn= and sunset at =dusk=.
+ You can get the book yourself. =I laid the book on that shelf=.
+ The dishes are almost ready. =Haven't you laid the table yet=.
+ It's nice to get up early. =It's nicer to lie in bed=.
+ I didn't get up early last Sunday. =I lay in bed till 10 o'clock last Sunday morning=.
+ After they finished trimming the lawn, =they've all lain on the grass=.
+ I have to get all these books in order. =To make matters worse, the room is rather small=.
+ She stared at it. You can also say =she gazed at it=.
+ You are not supposed to read novels at work. =You can do it in your spare time=.
+ =He thinks very highly of me=. And I'll try my best not to fail him.
+ He crossed the street in such a hurry. =He was nearly run over by a car=.

* NCE2 Lesson53
+ It didn't cost much to repair the castle. =Damage was confined to a small portion of it=.
+ Look at that model girl over there, =she must has the perfect body proportion=.
+ If you all do not have a better solution, =I have a proposition=.
+ They have put out the forest fire, but they still need to find out =how the fire began=. However, a fireman accidentally =discovered the cause=.
+ Cigarette butts can also be called =cigarette ends=.
+ He noticed the remains of a snake =which was wound round the electric wires of a 16,000 volt power line=.
+ The strange phenomenon baffled all of us, but finally =he solve the mystery=.
+ A bird had =snatched up= the snake and =dropped it on to= electric wires.
+ In order to persuade him to change his mind, =I reasoned with him for hours=.
+ The smoke has come out, when =I smelled something burning=.
+ =On my going to= the kitchen, I found it full of smoke.
+ I was busy mixing butter and flour and my hands were =covered with stick pastry=.
+ At that time, they always laughed at me. =Nothing could have been more annoying=.
+ I went to open the door eagerly, but =I was dismayed when I found out it was not her=.
+ Some doors do not have =doorknob= on the outside.
+ I had no sooner got back to the kitchen than doorbell =rang loud enough to wake the dead=.
+ The postman wanted me to =sign for a registered letter=.
+ That event =prompted me to write= a letter to him.
+ I'm very pleased =to learn that= you a well.
+ In a letter, the first paragraph should be =Thank you for letter=.

* LTT1 Lesson15
+ What flights =are there= from London to Vienna tomorrow? I'd like to travel =first class=, please.
+ Would you =care= for some cake?
+ I think I will choose the curry. What would you like =afterwards=?
+ Smoke? No thanks, I'm trying to =cut down=.
+ I'm looking for a room. Let me see, I have just got a =vacancy=. Great, what =sort of= price are you =asking=?
+ He is =fully booked= till 11 unless there is a =cancellation=. Is 12:50 convenient?
+ Can you =fix= me =up with= a part-time job? Anything =in= particular that =appeals= to you?
+ A table for one, please. I will have the =set lunch= and the soup =for the day=. Plaice for the =main course= and apple tart =to follow=. Finally, =larger= to drink with the meal.
+ I have a table for two under the name of Black Moore. / Will this table do for you?
+ Half of =bitter= for me.
+ I'd like to =start with= prawns and rack of lamb to follow.
+ How would you like your steak done, sir? =Medium rare=, please. / Raw - uncooked; Blue rare or very rare - cooked very quickly, outside =seared=, but inside =barely cooked=; Rare - gray-brown outside, red inside and slightly warm; Medium rare - fully red, warm center; Medium - hot, red and pink inside, gray-brown outside; Medium well done - pink inside; Well done - gray-brown throughout and slightly =charred=.
+ Half =carafes= means half bottles.
+ I worked =over-time= and I bought the =racing cycle= my self.
+ He is making my life =a misery=.
+ I shouldn't =wear= makeup. Natural beauty is the best. Sometimes he even interferes =with= my homework.

* LTT1 Lesson16
+ How should I do it, sir? Just =tidy= it =up a bit= and =nothing at all=, please.
+ Is anybody =looking after= (attending to) you, sir? No, I'm after a =V-neck pullover= in gray.
+ I should imagine so.
+ How much is it? 75 =pence= (pennies) =exactly=, please.
+ What's wrong with me, doctor? I should say you are generally run down.
+ Don't smash down the door, I have the key! / I accidentally =knock over= my son's lofty tower and the =building blocks= fell out(scattered) everywhere. / The car run him down. / The Canadian army =took down= the barricades =erected= by the Indians.
+ How do you =find things over= this place? If it wasn't for the climate, I like it very much. It won't =take you long= to settle down.
+ I can give you a lift, I'm going right =past= your place.
+ Can you turn the radio down =a fraction= (a little bit)?
+ Wouldn't it be an idea to buy you own soap? Sorry, I didn't realize you feel so =strongly= about it (it bothers you that much).
+ =Snack bar= usually serves fast food.
+ Maxi Quarterpounder with chips
+ We are not =licensed= to sell =alcohol=.
+ We are leaving =first thing= tomorrow. How =on earth= can I get it cleaned? You can =handed it in= for dry cleaning before 9.
+ I have to get up early tomorrow, so I'll be needing =an early call= tomorrow. Can you =fix that= for me?
+ That's how you do it, but how was I supposed to know.
+ My wife is driving tonight so I need something strong.
+ That's enough, I'm =fed up= with this job! There is no =variety= in our *lives*. You need a holiday. That's =what's the matter with= you.
+ What was the =worst= problem you =encountered= in your present job? How did you =handle= it?
+ What are you most =proud of= having done in your present job?
+ Why do you think you are =qualified for= this job?
+ What sort of boss would you most like to =work for=?
+ Supposing a member of your =stuff= was frequently =away from= work, =claiming= to be ill. What action would you take?
+ If you were working =as part of= a team, what =unspoken rules of behavior= would you observe?
+ How long do you plan to =stay in= this job?
+ =sitting= room (living room) / dinning room
+ He has won a prize =from= a competition.
+ Sometimes is not easy to locate the matching =parenthesis=.
+ You can call hotel =receptionist= or =room service= you need anything.
+ What ought I to do?

* LTT1 Lesson17
+ When the coupon is used =in conjunction with= credit card, an identification is =mandatory=.
+ That will be eighty-five pence =in all=.
+ And while I =think of it=, please ask when you borrow the iron. I really ought to =have known better=, sorry.
+ It's =bound= to be strange at first.
+ It's time we =were off=, thanks for the wonderful meal.
+ Can I give you a lift?" "Isn't it =out= of your way?"
+ How long have you had it? The =best part= of a week. =By the sound of it=, you've got a chill.
+ condiments and spreads - peanut butter, mustard, soy sauce, vinegar, chutney, ketchup, sweet spreads, lemon curd, marmalade.
+ I'd like to =reserve= a table for two, please. =Was= that today and what time =was= it?
+ too many white clouds
+ We =are stuck= here, we can't take off!
+ London school teachers =protested about= their salaries and =conditions=. They are now on their second week of =strike= for =better pay=.

* LTT1 Lesson18
+ I actually don't =feel like= one at the moment, thanks.
+ I believe you =take in= foreign students. Yes, if you don't mind sharing.
+ Will Friday do?
+ I wonder whether the dentist could =fit= me =in= tomorrow. I'm afraid there is =nothing= before midday.
+ I =was= wondering whether you needed any part-timers. What were you thinking of?
+ There is nothing at present, but =look back= in week.
+ How do you like it, sir. Just a trim, please.
+ What have you got =in the way= of brown =suede= jacket?
+ Hold the line(hold on), please.
+ I'll just see if she is in. Right you are.
+ I'm spending a few month =brushing up= my English and getting to know the country better.
+ I'm keen on getting some experience abroad.
+ Well, you'd find it =rather different= here, we have only ten tables. That must be very =cozy=. We try to create a warm =intimate atmosphere=.
+ You'll be working =directly under= me.
+ look after the bills
+ The usual question - what sort of salary were you thinking of paying?
+ I like to see your actions so to speak.
+ What's the forecast.
+ =Come off it= (save it), Mulligan. For a start, you spent three days watching the house.
+ The neighbors got =suspicious= and phoned the police.
+ You should've worn gloves. We find your finger print on the jewels.
+ If you'd(had) =taken up= burglary, you'd(would) have made a fortune.
+ I get more =black eyes= than goals.
+ On dry hard football =pitches= they break their bones; on muddy ones they =sprain= their =muscles=.
+ =Down with= football, I say.
+ Let me see, that is a =bad= cut. I'll put a =plaster= on it, but you'll have to see a doctor.
