#+TITLE: English
#+AUTHOR: Gu Feng
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/code-hover.css" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/org.css" />
#+HTML: <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

* Godzilla
+ The Godzilla is no longer =terrestrial=, it's =airborne=.
+ This is our =needle in the haystack=, but it is =imperative= that we find it.
+ Welcome, glad to =have you on board=.
+ =My condolences=, I'm really sorry for your loss. I sent him =a letter of condolences=.
+ =Parasitic spores=, one =dormant=, but the other =hatched=. =Catalyzed= by a mining company =unknowingly drilled into its tomb=.
+ =The hatchling burrowed straight for= the nearest source of radiation, =the power plant=, and =cocooned= there for 15 years, absorbing its =radioactive fuel= to =gestate=, to grow.
+ The creature have electrical effect on everything =within a close proximity=.
+ Anything =at all= would help us.
+ Where is it =headed= now? / I'm =headed= to Hawaii.
+ For the =comfort= of others. / For others' =sake=.
+ We've just received =an intel report= from the intelligence.
+ The ship appears at 50 =nautical miles= northwest.
+ Some ship is asking for help, we are =picking up a distress= signal.
+ They =are headed= to the beacon.
+ The =chameleon= survives by =blending in with= its background. / =Chameleons camouflage= themselves =in a variety of= different ways. / Chameleon's =disguise(camouflage)= is like magic.
+ Look, I've got a =ping=. Never mind, it's probably just a =glitch=. I got a =reading= again, it's =right up ahead=.
+ This is a direct command from the =General quarters=.
+ The plane is landing, I'm going up to the =flight deck=.
+ We are =circling= the target. Stand by, got a =visual=.
+ AIDS is a universal bogey.
+ Run! =Tsunami=!
+ There was another spore, =intact=. But we =vivisected= it and it was =disposed of=. / This is the safest =means of disposing of nuclear waste=.
+ They are =converging= here, we just wait for them.
+ Regular bomb can't kill them, we can =rig a nuclear warhead with a shield timer=.
+ The radiation =lures= MUTOs.
+ We =detonate= the bomb in desert, with minimal =fallout risk to= the city.
+ You can't be serious, they =feed on= radiation.
+ If you have any other ideas, =I'm all ears=.
+ My first =priority= is to =safeguard= our citizens.
+ The watch is =stopped=.
+ Everybody =disembarked=! / Soldiers, =dismiss=!
+ Locals are =being urged to please find shelter=, =stay indoors= and =stay off= the road.
+ After the explosion, there are =debris= everywhere.  / Many people close to the explosion were kill by the =shrapnel= of the bomb.
+ This bomb makes the old one look like a =firecracker=. Nothing can =withstand that blast=.
+ Many Americans think their legal system has =gone haywire(chaotic, disordered, out of order)=.
+ This suit is obviously to fashionable for him, he is really an =old school=.
+ You can always make the old watch work. =Take a licking, keep on ticking=.
+ We must hurry, it has =outrun= us.
+ This is a direct order from the =tactical operations command=.
+ I =retrofitted= that device myself.
+ =With all due respect=, may I ask what's the second plan?
+ We tied the boat =to the pier=. / They went for a =stroll= along the =waterfront=. / The ferry attempted to =dock on= the island. / The =harbor= admits large =tankers and freighters=.
+ If the MUTOs have =spawned=, they will be building a nest.
+ When you find the =warhead=, how long can you =disarm= it?
+ They have all =been briefed=, we have no =extraction plan=.
+ Sir, I'll do =whatever it takes=. / We must drive out the enemy =at all costs=.
+ The monster is an =alpha predator=.
+ We haven't lost yet, we may still =have a chance=. / I thought I might =have a shot=.
+ The =arrogance= of man is thinking that nature is in our control and =not the other way around=.
+ We are still trying to open it, but it's not =budging=, it's =sealed shut=.
+ Find the =ignition= and start this boat.

* LTT1 Lesson1-3
+ NAmE:vest BrE: =waistcoat= / NAmE:closet BrE: =cupboard= / NAmE:sink BrE: =washbasin= / NAmE:apartment BrE: =flat= / NAmE:rinse BrE: =swill= / At least =rinse= your mouth.
+ =So off they went=, headed to the next destination.
+ He saw me at a distance and =came up to= me immediately. / The name =came up= a lot in the discussion. / New year is =coming up= soon. / Call me if anything =comes up=. / The house =comes up= for sale. / New jobs will =come up= soon. / He always =comes up with= new ideas. / I don't think he can =come up with= any money.
+ What happened to him? He is =looking upset=. / You are =looking good= in this dress. / Do I know him? He =looks familiar=.
+ The table is covered with =a piece cloth=. / I need to change my =clothes=. / What is your favorite =item of clothing=?
+ I spilled the water. BrE: =spilt= / Tonnes of oil =spilled from= the tank. / The words =spilled out in a rush=. / Some jobs are likely to have a negative =spillover into= family life. / The drug has unknown =side effect=. / This article has =negative impact= on readers.
+ My wife is =laundering clothes= in the =launderette (laundrette, NAmE:laundromat)= at the street corner. / It's illegal to =launder ill-gotten= money. / My clothes are all dirty, I'm going to =do my laundry=.
+ It's none of their business, they are just =outsiders from off the street=.
+ He wanted me to jump, I'd rather not.
+ I've got a headache, I need some =aspirins=.
+ I like =suspense= movies, especially =Hitchcock's=!
+ I have to go to work now, but I can't find my =overall=.
+ They should start saving their =pocket money=, I'll create a =savings account= for them. / During holiday, most students will =take part time jobs= to make some =spending money=.

* NCE2 Unit1
+ His private life =came under media scrutiny=. / All citizens in the nation =are subject to= the law. / Governments must be =open to public scrutiny=.
+ She spent a lot of money on the crap, so I got =very angry= with her.
+ I =turned round(around)= and looked at them angrily, but they did not =pay any attention=.
+ I never =get up early on= Sundays. I sometimes =stay in bed= until lunchtime.
+ Just then, the telephone =rang=.
+ You can't give them everything they want, you =spoil= them!
+ I visited =museums= and =sat in= public gardens.
+ He =taught me a few words= of Italian.
+ I’ve never been =abroad= before.
+ =In a way(in some way, in one way)=, television is more =challenging= than theater.
+ The chair is =in the way=, move it!
+ I =ran into= them on the way home. / The bank =ran into= financial difficulties. / Our debts are running into millions of dollars.
+ He's the man who =goes through= his whole life =blending into the wallpaper=, =seemingly content= to work hard =day-in and day-out= and =leave the spotlight to others=.
+ He has sent =a great many requests for= spare parts. / Can you =spare= me a moment?
+ They went =on a short excursion= into the forest. / Seems she has gone on =an excursion= into non-related topics.
+ =Up to now(up till now)=, I haven't been abroad even once.
+ The beggar =stood on= his head and sang songs.
+ He =calls at= every house once a month. / I’ll =call for= you(pick you up) tomorrow 8 pm.
+ Bags have difference size. =Knapsacks= are big, =backpacks= medium and =shoulder bags= are usually small.
+ The robbers =rushed out= of the bank and =took off= in their car. / =Take off= your shoes! / The new magazine has soon =taken off= (become very popular). / The plane accelerated down the runway for =take-off=. / The film is a =take-off= (copying) of Star Wars.
+ They usually =knock off= (get off work) around five to drink beer. / I =knocked= the lamp off the table. / The shop assistant =knocked= 10% off the bill.
+ Try not to =knock= that vase over.
+ The blows =knocked me out= (stunned me).
+ a =bag= of flour / a =tube= of toothpaste / a =flowerpots= with plastic plants / two tall, shapely brass candlesticks
+ the customs house / customs invoice / the level of =customs duties= (tariff) on imports / a customs officer / Arriving =refugees= were =whisked= through customs.
+ Two detectives were =keeping guard= at the door.
+ =To their surprise=, the parcel was full of stones and sand!
+ =Just as= they were chatting, the boss entered.
+ Everybody in the town =enters for= the competition each year. / He will be =taking part in= an important race.
+ He has built a =neat= path and a wooden bridge =over= a pool.
+ I always win a little =prize= for the worst garden in the town.
+ What does the phrase =refer to=?
+ a large =crowd= of people
+ The minute/hour/second =hand= did not move.
+ The spoon is =made of= silver / Glass is =made from= sand and lime. / This is one of those applications that PDAs were =made for=. / You two are just =made for= each other.
+ He came to me and =whined about= his trouble for hours. He is really a =whiny= man. / People get rude and whiny when they are exhausted.
+ "One good turn deserves another."
+ He has a interesting job and also get a good salary.
+ I will =pay you back (repay you)= (pay it back to you) soon.
+ The captain will =sail from= Portsmouth to France tomorrow.
+ It’s =up to you= to make the final decision. / I don’t think he is =up to= the job. / The total number is =up to= 3 million. / I can take =up to= four people in my car. / up to now (up to this time) / What have you been =up to= recently? / You think your idea is =up to= mine?
+ This is the =final call for boarding on= (final boarding call of) flight MU 7766. 
+ The police always have =a difficult time= on these occasions, trying to =keep order= of the events.
+ by walk =by walking =on foot =by foot / by bus / by car / by train / by sea / by air
+ I don’t =take= orders. / You are no king to me!
+ Single quotation marks looks like =apostrophes=. / double quotation marks / The article starts with a =quote= from the Bible.
+ He waved to me and asked me for a lift.
+ =Apart from= (Except for) a few words, I don’t know any French at all.
+ You needn’t salute me. / He raises his arms in a triumphant salute. / He nodded a salutation.
+ A financial aid is available.
+ Soldiers =tramping= through the streets. / The =tramp= of marching feet is so loud. / She is a =tramp (whore, prostitute, promiscuous woman)= (slut) who sleeps around. / He is a =tramp (vagrant)= (beggar) off the street. / They start off on a =tramp= (trek) over the mountains.
+ It's a typical hero vs. =villain= movie.
+ Remember me to your parents.
+ The President's envoy =set off on= another diplomatic trip. / They =set off for= (set out to) a remote place. / Their escape =set off= (sound) the alarm. / Who =set off= the fire extinguisher? / Who =set off= the bomb? / The arrival of the charity van =set off a minor riot= as villagers =scrambled for= a share of the aid. / The joke =set him off= laughing. / Blue suits you, =sets off= the color of your hair.
+ I'm innocent, he =set= me =up=! / You =stood me up= (blew me off)!
+ Locals =looked on= (look at it) in surprise as hitch-hikers, cyclists, bikers, cars, vans and minibuses =filled up= the village square.
+ =Pop and folk singers and musicians= all attended the Grammy. / Waiters' job is to =attend to= customers.
+ She seemed =irritable(always loses temper)= (easily made angry), and annoyed with my every move. / Exams make me =nervous=, restless or uneasy.
+ I don't go on a vacation often, I can’t =afford= the time and money.
+ This note is only a =reminder=. / She gulped down the =remainder= of her coffee.
+ Just =let it go= (stop thinking about it all the time). / =Let it go of me= (Let me go)!
+ Despite of their appearances, traffic police are sometimes very polite.
+ I don't love you =in spite of= that, I loved you because of that.
+ He is a millionaire and he never wears =ready-made= suites. / Coco Channel was oringinally a =milliner=.
+ I can’t pay the bill, I =haven’t got= (have lost) my bag.
+ =Give in= your exercise book. / He can hardly bear it anymore, he will soon =give in, give up, ,surrender= / You have to =give up= (quit) smoking.
+ A sign with =an exclamation mark= on it means warning.
+ The play may begin =at any moment now= (real soon). / "We’ve sold out," the girl said. "What a pity!" Susan =exclaimed=.
+ I =might as well= have them, as I don't have other choice.
+ She took care of her =bed-ridden= grandma for years. / The refugees lived in =disease-ridden= environment.
+ He suffered =considerable= pain. / He suffered from a painful and =lingering= death.
+ She wanted to play the =martyr to= the society. / She was =martyred= for her faith.
+ This does not =worry= me anymore.
+ I was totally confused back then, but the professor =set me straight=.
+ I’m even less lucky.
+ Aeroplanes are slowly =driving me mad=.
+ It is not used before. Last year, however, it =came into use=.
+ People have been driven away from their homes, but I’m =determined= to stay. / He drives his car very badly. / Our army drove the enemy back.
+ Both girls write to each other regularly now.
+ He congratulated me =on= having got engaged.
+ Did anything emerge =from= your discussion?
+ I dreamt =of= you last night.
+ You can never rely =on= him to be punctual(on time). / He is a *liar*, he is not =trustworthy=. / I suppose I can =count on= you for help =in(with)= this matter. / You can depend =on= me.
+ I insist on you telling me the truth.
+ They can only cure him =of= his illness if they operate =on= him.
+ I haven't accused him =of= anything, but I suspect him =of= having taking it.
+ We expect a great deal =of(with)= you.
+ My hands smell =of= soap.
+ We have embarked =on= a new scheme.
+ I believe in taking my time.
+ She prides herself =on= her clean house.
+ We must =economize on= fuel. / Cycling is more =economical= than driving. / She lives a =frugal= lift. / Backbone members are more likely to survive a =stuff cutback=. / The government's deficit is so high that we need a =cutback in public spending=. / Customers are =drawing(pulling) in their horns= at a time of high interest rates. / Cuts in defense spending forced the aerospace industry to =retrench=. / He needs to =scrimp and save (tighten his belt)= while looking for a job. / =Scrimping on= safety measures can be a false =economy=. / Many families must =skimp on= their food and other necessities just to =meet= the monthly rent. / He never =stint on= wining and dining. / To avoid having to =stint= yourself, =budget= in advance. / His boss is =stingy= and idle.
+ He =undertook= that challenging job. / My left knee is very =susceptible to= injury (*injury-prone*). / My jacket is water =proof=./ She is =apt to= (often) talk loudly. / Such thing is really =liable to= (likely to) happen.
+ Economy is often =subject to= politics. / The man =subjected= her wife =to= four years of *beatings and abuse*.
+ He headed south after a =stint= in that village.
+ The administrator is =holding back= (waiting) for several reasons.
+ He doesn't have a job, he lives =on= his mother.
+ He was employed =in= that factory.
+ I can assure you =of= my support.
+ Do you approve =of= hunting.
+ I despair =of= ever loving him! / Being desperate is the feeling of =despair= and =inadequacy=. / She wrote to him in =desperation= before the suicide.
+ He delights =in= annoying me.
+ She is really pessimistic and always =pours(throws) cold water (put a damper) on= our ideas.
+ He felt very upset and started to complain about this wicked world, but was interrupted by a knock =at= the door.

* NCE2 Lesson53
+ It didn't cost much to repair the castle. =Damage was confined to a small portion of it=.
+ Look at that model girl over there, =she must has the perfect body proportion=.
+ If you all do not have a better solution, =I have a proposition=.
+ They have put out the forest fire, but they still need to find out =how the fire began=. However, a fireman accidentally =discovered the cause=.
+ Cigarette butts can also be called =cigarette ends=.
+ He noticed the remains of a snake =which was wound round the electric wires of a 16,000 volt power line=.
+ The strange phenomenon baffled all of us, but finally =he solve the mystery=.
+ A bird had =snatched up= the snake and =dropped it on to= electric wires.
+ In order to persuade him to change his mind, =I reasoned with him for hours=.
+ The smoke has come out, when =I smelled something burning=.
+ =On my going to= the kitchen, I found it full of smoke.
+ I was busy mixing butter and flour and my hands were =covered with stick pastr=.
+ At that time, they always laughed at me. =Nothing could have been more annoying=.
+ I went to open the door eagerly, but =I was dismayed when I found out it was not her=.
+ Some doors do not have =doorknob= on the outside.
+ I had no sooner got back to the kitchen than doorbell =rang loud enough to wake the dead=.
+ The postman wanted me to =sign for a registered letter=.
+ That event =prompted me to write= a letter to him.
+ I'm very pleased =to learn that= you a well.
+ In a letter, the first paragraph should be =Thank you for letter=.

* LTT1 Lesson15
+ What flights =are there= from London to Vienna tomorrow? I'd like to travel =first class=, please.
+ Would you =care= for some case?
+ I think I will choose the curry. What would you like =afterwards=?
+ No thanks, I'm trying to =cut down=.
+ I'm looking for a room. I have got a vacancy. What sort of price are you asking?
+ He is =fully booked= till 11 unless there is a =cancellation=. Is 12:50 convenient?
+ Can you =fix me up= with a part-time job? Anything in particular that =appeals= to you?
+ A table for one, sir? / Are you having the set lunch? / What's the soup for the day? / And for you main course? / Plaice and apple tart to follow. / And larger to drink with the meal.
+ I have a table for two under the name of Black Moore. / Will this table do for you?
+ Half of bitter for me.
+ I'd like to start with prawns and rack of lamb to follow.
+ How would you like your steak done, sir? =Medium rare=, please. / Raw - uncooked; Blue rare or very rare - cooked very quickly, outside seared, but inside barely cooked; Rare - outside gray-brown, red inside and slightly warm; Medium rare - fully red, warm center; Medium - hot, red and pink inside, gray-brown outside; Medium well done - pink inside; Well done - gray-brown throughout and slightly charred.
+ Half =carafes= means half bottles.
+ I worked =over-time= and I bought the =racing cycle= my self.
+ He is make my life =a misery=.
+ I shouldn't =wear= makeup. Natural beauty is the best. Sometimes he even interferes =with= my homework.
