#+AUTHOR: Gu Feng
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/code-hover.css" />
#+HTML: <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

* It didn't cost much to repair the castle. =Damage was confined to a small portion of it=.
* Look at that model girl over there, =she must has the perfect body proportion=.
* If you all do not have a better solution, =I have a proposition=.
* They have put out the forest fire, but they still need to find =how the fire began=.
* Cigarette butts can also be called =cigarette ends=.
* They have been trying to find out how the fire began. However, a fireman accidentally =discovered the cause=.
* He noticed the remains of a snake =which was wound round the electric wires of a 16,000 volt power line=.
* The strange phenomenon baffled all of us, but finally =he solve the mystery=.
* A bird had =snatched up= the snake and =dropped it on to= electric wires.
* In order to persuade him to change his mind, =I reasoned with him for hours=.
* The smoke has come out, when =I smelled something burning=.
* =On my going to= the kitchen, I found it full of smoke.
* I was busy mixing butter and flour and my hands were =covered with stick pastr=.
* At that time, they always laughed at me. =Nothing could have been more annoying=.
* I went to open the door eagerly, but =I was dismayed when I found out it was not her=.
* Some doors do not have =doorknob= on the outside.
* I had no sooner got back to the kitchen than doorbell =rang loud enough to wake the dead=.
* The postman wanted me to =sign for a registered letter=.
* That event =prompted me to write= a letter to him.
* I'm very pleased =to learn that= you a well.
* In a letter, the first paragraph should be =Thank you for letter=.

