#+AUTHOR: Gu Feng
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/h2-text-hide.css" />
#+HTML: <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

+ It didn't cost much to repair the castle. =Damage was confined to a small portion of it=.
+ It didn't cost much to repair the castle. =Damage was confined to a small portion of it=.
+ It didn't cost much to repair the castle. =Damage was confined to a small portion of it=.

+ It didn't cost much to repair the castle. =Damage was confined to a small portion of it=.
+ It didn't cost much to repair the castle. =Damage was confined to a small portion of it=.
+ It didn't cost much to repair the castle. =Damage was confined to a small portion of it=.
*** Look at that model girl over there, =_____=.
  she must has the perfect body proportion
* If you all do not have a better solution, =_____=.
  I have a proposition
* They have put out the forest fire, but they still need to find =_____=.
  how the fire began
* Cigarette butts can also be called =_____=.
  cigarette ends
* They have been trying to find out how the fire began. However, a fireman accidentally =_____=.
  discovered the cause
* He noticed the remains of a snake =_____=.
  which was wound round the electric wires of a 16,000 volt power line
* The strange phenomenon baffled all of us, but finally =_____=.
  he solve the mystery
* A bird had =_____= the snake and =_____= electric wires.
  snatched up
  dropped it on to
* In order to persuade him to change his mind, =_____=.
  I reasoned with him for hours
* The smoke has come out, when =_____=.
  I smelled something burning
* =_____= the kitchen, I found it full of smoke.
  On my going to
* I was busy mixing butter and flour and my hands were =_____=.
  covered with stick pastry
* At that time, they always laughed at me. =_____=.
  Nothing could have been more annoying.
* I went to open the door eagerly, but =_____=.
  I was dismayed when I found out it was not her.
* Some doors do not have =_____= on the outside.
  doorknob
* I had no sooner got back to the kitchen than doorbell =_____=.
  rang loud enough to wake the dead
* The postman wanted me to =_____=.
  sign for a registered letter
* That event =_____= a letter to him.
  prompted me to write
* I'm very pleased =_____= you a well.
  to learn that
* In a letter, the first paragraph should be =_____=.
  Thank you for letter
