#+AUTHOR: Gu Feng
#+TITLE: IELTS SENTENCES
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/code-hide.css" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/org.css" />
#+HTML: <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
#+OPTIONS: toc:1

*                                                                 :education:
** 从入学第一天起学生就要遵守校规 =On the first day a pupil enters school, he is asked to conform to the school rules.=
** 寄宿学校学生学会合作和互让,为以后成功培养人际交往能力 =In a boarding school, students learn to cooperate and compromise, and develop interpersonal skills needed for future successes.= #
** 取长补短 =learn from other's strong points and overcome our weakness=
** 盲目/机械地照做 =copy things blindly/mechanically= #
** 纪律不会扼杀天才而恰恰相反 =Discipline does not kill one's talent, quite the opposite in fact.= #
** 其实正相反,压力扼杀创造力 =On the contrary, I think pressure stifles creativity.=
** 消除误解 =correct misapprehension=
** 养育孩子 =bring up children=
** 出国留学开阔视野充实思想培养自立 =Overseas study broadens one's vision, enriches one's mind and cultivates independence.=
** 学生认为老师说的不对提出质疑 =Once students think what a teacher says is not correct, they defy him.=
** 远程教育和传统教育互补 =Tele-education and traditional classroom teaching complement each other.= :technology:
** 挑战权威 =challenge the authority=
** 学生应该专心学习,兼职可能会分散注意力 =A student should concentrate his/her attention on academic study and taking a part time job may divert his/her attention.=
** 大学生应该更关心公共事务 =College students should concern themselves more with public affairs.=
** 穿校服提高成绩应该普及 =School uniforms increase attendance and academic achievements, so the practice of wearing uniforms at school should be popularised.= #
** 父母烦恼与孩子游戏成瘾 =Parents are annoyed with children's addiction to computer games.= :technology:
** 年轻人学会花钱避免浪费 =Young people should learn to spend money carefully and avoid extravagance.= #
** 不可否认学校该禁烟 =It's undeniable that smoking should be banned in school.=
** 学术不端 =academic misconduct=
** 他表现勇敢 =He behaved with great courage.=
** 年轻人沉静其中而没有意识到他们有多努力 =The youngsters were so absorbed in it and did not realise how much they are exerting themselves.=
** 不要做无用功 =Do not exert yourself unnecessarily.=
** 应该教育儿童遵守法律 =Children should be taught to abide by the law.= :crime:
** 农村儿童没钱上学成文盲 =In rural areas, many children can't afford to go to school and become illiterates.=
** 沉溺电脑游戏严重影响学习 =Indulgence in computer game will affect one's academic performance seriously.= :technology:
** 为了吸引人们从事教育,专家主张提高工资 =In order to attract more people to take up teaching as their lifelong pursuit, some experts advocate higher salaries for teachers.= #
** 考生没通过考试不会被录取 =If a candidate fails in the IELTS test, he/she will not be admitted into a university in Australia.= #
** 老师不该因为家长的错误而责备孩子 =A teacher should not blame a child for his/her parents' fault.=
** 理论联系实际 =apply theory to practice=
** 有父母在国外的儿童在18岁时没有资格接受免费高等教育 =Children who attain the age of 18 whilst a parent is abroad will not be eligible for free higher education.=
** 克服坏习惯 =conquer/break/overcome bad habit=

*                                                               :environment:
** 为后代保护林地 =We must conserve our woodlands for future generations.=
** 粗放灌溉消耗宝贵水资源 =Extensive irrigation consumes our scarce freshwater resources.=
** 有效防范能够控制人口增长减轻环境压力 =Effective precautions can help the control population growth and alleviate environmental pressures= #
** 把耕地作为开发区的政策受到严厉批评被视为不环保 =The policies of turning tillable fields into development zones have been severely criticized and regarded as environmentally unfriendly/environment-unfriendly.= #
** 教育公民珍惜水不要浪费水资源 =Citizens should be educated to cherish every drop of water and never lavish our scarce freshwater resources.=
** 再次欠收将是农民的灾难 =It's would be a calamity for the farmers if the crops failed again.=
** 酸雨激发环保意识 =Acid rain arouses people's awareness of environmental protection.=
** 沙漠化损失估计上百万 =Damage caused by desertification was assessed at millions of dollars.=
** 政府努力实现资源可持续发展 =Governments should endeavour to achieve sustainable development of resources.=
** 砍伐森林导致动物灭亡 =The deforestation will drive animals without the adaptability to new surroundings into mass extinction.= :animal:
** 生态系统崩溃 =breakdown of the ecosystem=
** 酸雨迫使人们呆在屋里 =Acid rain compels people to stay indoors.=
** 含有污染物 =contain contaminants=

*                                                                    :health:
** 食荤者为了营养吃肉 =As for proponents of meat eating, absorption of nourishment is the major reason for them to have meat.= # :animal:ethics:
** 身体垮掉 =Overwork may finally lead to breakdown in heath.=
** 无数研究证明吸烟有害健康 =Numerous research and studies confirm the theory that smoking does harm to health.=
** 现代医学攻克很多疾病 =Modern medical science has conquered many diseases.= :technology:
** 快餐吃多了有害身体 =Eating too much fast food is physically damaging, for fast foods contain to much sugar, fat and calories.=
** 过分沉溺于电脑游戏导致近视,肥胖和重复性损伤 =Overindulgence in computer games contributes to myopia, obesity and repetitive stress injuries.=
** 过早地处于亚健康状态 =be in the state of sub-health prematurely=
** 身患绝症 =suffering incurable/terminal disease=
** 克隆技术帮助治愈遗传疾病使人们过上健康生活 =The cloning technology would help scientists to cure genetic diseases and also other diseases so that people can live longer healthy lives.= :technology:
** 微恙 =trifling ailment=
** 以肉奶为主的饮食习惯会引发各种慢性病和生理失调 =Meat and dairy centred diets are linked to many types of cancers, as well as chronic diseases such as heart ailments, diabetes, obesity, gallbladder diseases, hypertension, and more deadly diseases and psychological disorder.=
** 充分意识到健康重要性,城市居民喜欢有氧运动 =Fully aware of the importance of health, many city dwellers adore aerobic exercise.=
** 要长寿建议养成健康饮食和锻炼习惯 =To enjoy a longer lifespan, it is advisable for us adopt and maintain healthy patterns of diet and exercise.=
** 压力扰乱免疫系统 =pressure disorder our immune system=              :work:
** 白领调整生活方式保持健康 =White-collar workers should adjust their lifestyle in order to stay healthy.= :work:

*                                                                    :ethics:
** 计划生育无可厚非 =China's family planning policy is above/beyond reproach.=
** 科学家谴责克隆人因为有悖伦理道德 =Many scientists condemn cloning human beings for it is morally and ethically wrong.= :technology:
** 正反意见抵消 =The pros and cons cancel out.=
** 令人震惊,无法容忍 =outrageous and intolerable=
** 受责任心,道德约束或至少法律的制约 =Manufactures should be subject to the sense of responsibility, moral obligation or at least the law.= #
** 随着第一只克隆羊的出现人类克隆违法自然的讨论加剧 =The discussion on whether the human race can go against nature by cloning themselves has heated with the advent of the first cloned sheep Dolly.= :technology:
** 废除死刑的争论 =There arises a heated debate on whether capital punishment should be abolished.=
** 在我背后说闲话让人恼火 =It vexed me to think of others gossiping behind my back.=
** 光阴一去不复返 =Nothing can compensate for the loss of time.=
** 为暴行赎罪 =The invaders must atone for atrocities they committed.=
** 运动员服用禁药并不少见 =Abuse of performance-enhancing drugs is not uncommon among athletes.= #
** 不充分讨论利弊无法评估毒品合法化必要性 =It's hard to make assessment on the necessity of drug legalisation if merits and demerits are not fully discussed.= :crime:
** 怀疑论者将其归因于生活的不公 =A sceptic may put it down to life inequalities.=
** 轻率的，无知的，懒惰的，只看事情表面的结果而不是事情本身，就会归功于运气、命运、和巧合 =The thoughtless, the ignorant, and the indolent, seeing only the apparent effects of things and not the things themselves, talk of luck, of fortune, and chance.=
*                                                                      :work:
** 开放办公环境使员工自由交流 =An open office environment makes workers communicate directly and freely.=
** 不接触同事不了解公司状况阻碍职业发展 =The lack of daily contact with coworkers could take us out of the loop relative to what is going on within the company. This lack of inside knowledge could affect our advancement within the company.=
** 人际关系紧张,工作压力大,竞争激烈导致白领精神崩溃 =Tense human relationships, heavy pressure from work and life and fierce competition contribute to many white-collar workers' nervous breakdown.= # :health:
** 勤劳简朴适应于一切事业 =The principle of diligence and frugality applies to all undertakings.=
** 过去几年在跨国公司积累丰富经验 =In the past few year, I've been working for a famous multinational and therefor attained fair knowledge and rich experience in this field.=
** 适应规范 =adapt to norms=
** 能够适应世界变化对个人很重要 =Learning to adapt to the changing world is of great significance to a person.= #
** 嘴上说说却从不付诸行动 =He always purport to do something but never act out.=
** 竞争激烈白领自杀数上升 =The number of white-collar workers who commit suicide increases with the increasingly intensive social competition.= :health:

*                                                                    :family:
** 夫妻间感性和理性需求与维持婚姻本身相比是次要的 =The emotional and intellectual needs of spouses are secondary to the survival of the marriage itself.=
** 宣布你们结为夫妻 =I now pronounce you husband and wife.= #
** 这个缺点抵消了本来还算开明的态度 =The weakness negates his otherwise progressive attitude.=
** 成功的婚姻归因于魅力,奉献和耐心 =A successful marriage can be ascribed to attraction, devotion and patience.=

*                                                                      :life:
** 业余爱好 =Leisure time pursuits influence one's thought-habit.=
** 期待广州之行愉快 =We anticipate great pleasure from our visit to Guangzhou.=
** 一部充满恐怖暴力但却引人入胜的电影 =a frighteningly violent yet compelling film=

*                                                                    :gender:
** 体力劳动几乎全部有男性完成 =Manual labour has been performed almost exclusively by men.=
** 最佳生育年龄 =prime child-bearing age=                              :work:
** 职业女性很难平衡工作和家庭 =Many career women find it really hard to balance work and family life.=

*                                                                    :animal:
** 熊猫和秃鹰被列为濒危物种 =Pandas and bald eagles are classified as endangered species.= #
** 邻居家养宠物的人们总是埋怨睡觉被吵醒 =People whose neighbours have pets always complain that their sleep is interrupted at midnight by the pets' noises.= :family:
** 与宠物的积极关系有助于建立与他人的信任 =Positive relationships with pets can be an aid in the development of trusting relationships with others.=
** 中国越来越多人加入到保护珍稀动物的运动 =More and more people in China have entered the campaign to save rare animals from extinction.=
** 动物保护人士反对为了人类利益虐待动物 =Animal activists assert their opposition to the fact that animals are abused for man's interests.=
** 虐待动物不道德 =It's unethical and barbaric to abuse animals.=

*                                                                :technology:
** 工序由电脑控制 =The process are all electronically controlled.= #
** 因特网是传播信息的便捷途径 =The Internet is a convenient way to convey information.= #
** 依靠无线技术发达国家实现远程教育 =Based on wireless technology, developed countries have realised the breakthrough of providing long distance education for children in remote areas.= :education:
** 互联网加速信息传播 =The advent of the Internet has accelerated the flow of information.=
** 宇航员圆满完成任务 =The astronaut has accomplished the mission successfully.=
** 成年人需要学习电脑 =With the application of computers, many adults feel the pressing need of acquiring computer literacy.=

*                                                                     :media:
** 代言系列美容产品 =The movie star endorses a line of cosmetic products.=

*                                                                   :culture:
** 人们年轻时开放年纪大后保守 =People tend to be more liberal when they are young and become more conservative as they get older.=
** 发展得当的话旅游业与保护古建筑不矛盾 =Carried out in the right way, tourism may not conflict with the conservation of historic buildings.=
** 文化遗产属于全人类 =Cultural heritage belongs to all human beings.=
** 封建迷信尽早废除,毒害人心 =The abolishment of superstitious practices and customs should be carried out as soon as possible since they may poison people's mind.= #
** 图书馆丰富的历史文化书籍能让市民了解国家的过去 =The abundance of historical and cultural books in libraries enables citizens to have an understanding of the countries' past.=
** 市民免费使用图书馆获得信息 =Citizens should have free access to the library so that they may get contact with the latest information.=
** 奥运会开幕被用于宣传 =The opening ceremonies of the Olympic Games are now used to publicise the host countries' accomplishment and reveal the countries' connotation.= #
** 老房子有魅力 =This old building has a lot of atmosphere.=
** 市政府应立项资助传统艺术家以弘扬独特本土文化 =The municipal government should approve a scheme which aims to subsidize traditional artists so as to carry forward our unique indigenous culture.= #
** 政府应筹划项目以挽救濒危语言 =The government should arrange for special programmes to save endangered languages.= :government:
** 语言学家有责任保护濒危语言 =Linguists assume new duties of storing as much information as possible about extinct languages.=
** 鼓励原住民坚持传统 =Aboriginals should be encouraged to adhere to their cultural traditions.=
** 我们永远不能放弃民族特性 =We shall never abandon our national identity.=
** 保护文化遗产,去糟取精 =The best way to protect our cultural heritage is to absorb the essence and discard the dregs.=
** 求同存异 =to seek common ground while reserving differences=
** 这篇文章除了长之外没什么不好 =The article is long, but not otherwise blameworthy.=
** 移民融入社区 =Immigrants try to assimilate into the community.=
** 欣赏不同文化 =appreciate a difference culture=
** 开阔视野 =broaden one's horizon=
** 扩大知识面 =broaden one's scope of knowledge=
** 开阔眼界 =broaden one's vision=
** 旅行开阔心智 =Traveling broadens the mind.= #

*                                                                :government:
** 过度消费导致严重赤字 =Excessive consumption resulted in heavy trade deficit.=
** 分配给公共教育的资金不该被滥用 =Funds allocated for public education should not be misused.= :education:
** 为无家可归者提供食宿 =afford food and beds for the homeless=      :ethics:
** 有争议的政策引来国际批评 =The controversial policy have attracted international censure.=
** 政府需要关注老年人需求多建养老院 =The government should attend to the needs of the elderly and more nursing homes should be established.= :development:
** 对零售商强制罚款 =Fines are imposed on retailers.=
** 解决办法就在政府手中 =The remedy lies in the hands of the government.=
** 卫生部门解决城市垃圾问题 =The health authority should take proper measures to deal with the increasingly serious rubbish problem in urban areas.=

*                                                                     :crime:
** 持续暴力使谈判进程减速 =Continuing violence will retard the negotiations over the country's future.=
** 他拒绝透露关于那个人的任何消息 =He refused to divulge any information related to/regarding/concerning/involving the man's whereabouts.=
** 谴责侵略,请求宽容 =denounce the invasion and plead for tolerance= #
** 青少年犯罪值得关注 =Juvenile delinquency is one of the several matters that claims the public attention.= :education:
** 被迫认罪 =Sometimes one might be coerced into pleading guilty.=
** 青少年吸毒归咎于无知和好奇 =We often attribute youth drug abuse to ignorance and curiosity.= :education:

*                                                               :development:
** 没有公司更够承担中国为敌的后果 =No company can afford to antagonize China.=
** 发展中国家与发达国家竞争世界市场 =Developing countries have to compete with developed countries for the world market.=
** 股票价格剧烈变动 =The stock price altered sharply.=

** 汽车自行车停路边严重阻碍交通 =Cars and bikes parked along the streets block the flow of traffic, sometimes leading to serious traffic congestion.= #
** 街道难容私家车 =The narrow streets can hardly accommodate the increasingly large number of private cars.=
** 控制平民获得武器途径 =control the flow of guns to general populace=
** 经济保持缓慢发展 =The economy remains sluggish.=
*                                                                    :letter:
** 感谢你发的培训小册子 =I shall appreciate it if you could send me some relevant booklets regarding the training programme.=

*                                                                     :bonus:
** sue complain grumble whine mutter murmur
** is secondary to
** but otherwise
** not uncommon
** ineffective half-measures
** if it were not for
** in fact quite the oppsite
* Sleeping on the Job
http://www.mensfitness.com/nutrition/sleeping-on-the-job-should-you-nap-at-work
Sleeping on the job boosts productivity.
Siestas company policy.
Daytime drowsiness can affect mood, productivity, and creativity, but a brief nap may provide greater alertness for several hours to help improve attention, concentration and accuracy.
Napping perk.
Cardiovascular disease and depression.
Sleep-deprived workers.
Stretching out.
Dozing in your cubicle.
Fool passersby into thinking you’re hard at work.
Drool on your report.
Our inner body clocks start to make us feel drowsy around siesta time—or somewhere between 1 and 4 p.m.—so aim to fit in a nap during these hours.
Make quick naps a daily ritual.
Get into the sleep mindset.
Doze off.
Snooze.
Catnaps.
Avoid snoozing too long and waking up groggy.
Longer naps have the downside of greater sleep inertia.
Set your cell phone or another device to go off after about 15 minutes.
You’ll feel recharged enough to tackle your afternoon agenda and still hit the gym after work.
