#+AUTHOR: Gu Feng
#+TITLE: IELTS SENTENCES
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/code-hide.css" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/org.css" />
#+HTML: <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
#+OPTIONS: toc:1

*                                                                 :education:
** 通过兼职学生们学会高效管理时间并且更加容易得到雇主青睐因为有工作经验 =Through taking part-time jobs, students also learn to manage their time efficiently and will be more marketable to future employers with work experience.=
** 一些大学生中断学业参军 =Some university students interrupt collage to serve the army.=
** 按能力分班伤害能力普通的学生 =Ability grouping injures the feeling of students of average performance.=
** 学校实行校服制度有助于形成强力的校风和对集体的归属感 =Schools implement uniforms to help create a strong sense of school ethos and a sense of belonging to a particular community.= :spell:
** 她英语和数学得了高分 =She gained high grades in English and Math.=
** 青少年不成熟且好奇容易盲从和模仿偶像 =Teenagers are immature and curious that they tend to follow blindly and emulate the behaviour of their idols.=
** 采用校服制度能够加强校园安全增强纪律和学习气氛 =The adoption of uniform policies can promote school safety, improve discipline and enhance learning environment.=
** 去美术馆培养儿童艺术品位丰富精神生活 =Visits to galleries help develop children's taste of art and enrich their spiritual life.= :spell:
** 年轻人决心出国留学开阔眼界学习技术能有光明前程 =Some young people determined to study abroad to widen their vision and learn advanced technology, so that they can have a bright future.=
** 从入学第一天起学生就要遵守校规 =On the first day a pupil enters school, he is asked to conform to the school rules.=
** 寄宿学校学生学会合作和互让,为以后成功培养人际交往能力 =In a boarding school, students learn to cooperate and compromise, and develop interpersonal skills needed for future successes.= :spell:
** 取长补短 =learn from other's strong points and overcome our weakness=
** 盲目/机械地照做 =copy things blindly/mechanically= :spell:
** 纪律不会扼杀天才而恰恰相反 =Discipline does not kill one's talent, quite the opposite in fact.= :spell:
** 其实正相反,压力扼杀创造力 =On the contrary, I think pressure stifles creativity.=
** 消除误解 =correct misapprehension=
** 养育孩子 =bring up children=
** 出国留学开阔视野充实思想培养自立 =Overseas study broadens one's vision, enriches one's mind and cultivates independence.=
** 学生认为老师说的不对提出质疑 =Once students think what a teacher says is not correct, they defy him.=
** 远程教育和传统教育互补 =Tele-education and traditional classroom teaching complement each other.= :technology:
** 挑战权威 =challenge the authority=
** 学生应该专心学习,兼职可能会分散注意力 =A student should concentrate his/her attention on academic study and taking a part time job may divert his/her attention.=
** 大学生应该更关心公共事务 =College students should concern themselves more with public affairs.=
** 穿校服提高成绩应该普及 =School uniforms increase attendance and academic achievements, so the practice of wearing uniforms at school should be popularised.= :spell:
** 父母烦恼与孩子游戏成瘾 =Parents are annoyed with children's addiction to computer games.= :technology:
** 年轻人学会花钱避免浪费 =Young people should learn to spend money carefully and avoid extravagance.= :spell:
** 不可否认学校该禁烟 =It's undeniable that smoking should be banned in school.=
** 学术不端 =academic misconduct=
** 他表现勇敢 =He behaved with great courage.=
** 年轻人沉静其中而没有意识到他们有多努力 =The youngsters were so absorbed in it and did not realise how much they are exerting themselves.=
** 不要做无用功 =Do not exert yourself unnecessarily.=
** 应该教育儿童遵守法律 =Children should be taught to abide by the law.= :crime:
** 农村儿童没钱上学成文盲 =In rural areas, many children can't afford to go to school and become illiterates.=
** 沉溺电脑游戏严重影响学习 =Indulgence in computer game will affect one's academic performance seriously.= :technology:
** 为了吸引人们从事教育,专家主张提高工资 =In order to attract more people to take up teaching as their lifelong pursuit, some experts advocate higher salaries for teachers.= :spell:
** 考生没通过考试不会被录取 =If a candidate fails in the IELTS test, he/she will not be admitted into a university in Australia.= :spell:
** 老师不该因为家长的错误而责备孩子 =A teacher should not blame a child for his/her parents' fault.=
** 理论联系实际 =apply theory to practice=
** 有父母在国外的儿童在18岁时没有资格接受免费高等教育 =Children who attain the age of 18 whilst a parent is abroad will not be eligible for free higher education.=
** 克服坏习惯 =conquer/break/overcome bad habit=
*                                                               :environment:
** 环保最重要的任务是培养对自然的热爱 =It is the top priority in the task of environment protection to nurture a love for nature.=
** 过度森林砍伐导致物种灭绝 =Excessive deforestation leads to the extinction of some species.=
** 做兼职培养竞争与合作意识,只对未来职业生涯是很必要的 =Taking a part-time job fosters competition and cooperation, which is quite necessary in one's future career.=
** 人类学习能力一部分是天生一部分靠培养 =The human organism learns partly by nature, partly by nurture.=
** 破坏自然植被 =damage natural vegetation=
** 应加强反对乱扔垃圾的法规并辅以重罚 =Strong anti-littering laws should be enforce effectively and backed by hefty fines.= :society:
** 核废料应妥善处理否则导致一系列严重问题 =Nuclear wastes should be properly disposed of; otherwise , it may give rise to a host of serious problems.= :technology:structure:
** 应该把更多基金用在淡水资源和濒危物种保护上 =More funds should be devoted to the conservation of freshwater resources and endangered species.= :spell: :animal:
** 为后代保护林地 =We must conserve our woodlands for future generations.=
** 粗放灌溉消耗宝贵水资源 =Extensive irrigation consumes our scarce freshwater resources.=
** 有效防范能够控制人口增长减轻环境压力 =Effective precautions can help the control population growth and alleviate environmental pressures= :spell:
** 把耕地作为开发区的政策受到严厉批评被视为不环保 =The policies of turning tillable fields into development zones have been severely criticized and regarded as environmentally unfriendly/environment-unfriendly.= :spell:
** 教育公民珍惜水不要浪费水资源 =Citizens should be educated to cherish every drop of water and never lavish our scarce freshwater resources.=
** 再次欠收将是农民的灾难 =It's would be a calamity for the farmers if the crops failed again.=
** 酸雨激发环保意识 =Acid rain arouses people's awareness of environmental protection.=
** 沙漠化损失估计上百万 =Damage caused by desertification was assessed at millions of dollars.=
** 政府努力实现资源可持续发展 =Governments should endeavour to achieve sustainable development of resources.=
** 砍伐森林导致动物灭亡 =The deforestation will drive animals without the adaptability to new surroundings into mass extinction.= :animal:
** 生态系统崩溃 =breakdown of the ecosystem=
** 酸雨迫使人们呆在屋里 =Acid rain compels people to stay indoors.=
** 含有污染物 =contain contaminants=
** 为提高产量农民使用硝酸盐杀虫剂和肥料对环境有害 =In order to increase the harvest, farmers uses nitrates, pesticides and fertilizers, which damage the environment.=
*                                                                    :health:
** 胆固醇高的人应该建议吃素以降低脂肪和胆固醇摄入 =Someone with a dangerously high level of cholesterol might be advised to follow a vegetarian diet to lower his or her fat and cholesterol intake.= :spell:
** 我们天生吃肉和菜,偏食不可避免会导致营养失衡 =We were made to eat meat and vegetables, cutting out half of this diet will inevitably mean we lose nutrition balance.=
** 为提高产量农民使用农药和杀虫剂对人类健康造成潜在威胁 =Farmers use all sort of fertilizers and pesticides to increase yields, which poses potential risks to human health.= :structure:
** 吸烟不仅危害你自己,而且会产生二手烟危害他人,使周围的人吸入二手烟 =By smoking, not only are you harming you self, but you are harming other by producing secondhand smoke, which will be inhaled by those around you.=
** 身体不好迫使她提前退休 =Bad health forced her into early retirement.=
** 克隆技术能延长寿命凭借替换无法的器官 =Cloning technology can extend people's life by creating human organs to replace those which fail to function.=
** 久坐的办公室生活对人们健康产生不良影响 =A sedentary life exerts an extremely bad influence on people's health.=
** 我们应该采用健康生活方式,比如减少咖啡因和酒精摄入(酒精实际上影响睡眠规律),休息充足,锻炼身体和劳逸结合 =We should adopt a healthy life style. For instance, limiting intake of caffeine and alcohol (alcohol actually disturbs regular sleep pattern), getting adequate rest, exercising, and balancing between work and play.= :spell: :structure:
** 科学研究表明吸烟会引发癌症和支气管炎 =Scientific studies disclose the fact that smoking may cause diseases such as cancer and bronchitis.=
** 食荤者为了营养吃肉 =As for proponents of meat eating, absorption of nourishment is the major reason for them to have meat.= :spell: :animal:ethics:
** 身体垮掉 =Overwork may finally lead to breakdown in heath.=
** 无数研究证明吸烟有害健康 =Numerous research and studies confirm the theory that smoking does harm to health.=
** 现代医学攻克很多疾病 =Modern medical science has conquered many diseases.= :technology:
** 快餐吃多了有害身体 =Eating too much fast food is physically damaging, for fast foods contain to much sugar, fat and calories.=
** 过分沉溺于电脑游戏导致近视,肥胖和重复性损伤 =Overindulgence in computer games contributes to myopia, obesity and repetitive stress injuries.=
** 过早地处于亚健康状态 =be in the state of sub-health prematurely=
** 身患绝症 =suffering incurable/terminal disease=
** 克隆技术帮助治愈遗传疾病使人们过上健康生活 =The cloning technology would help scientists to cure genetic diseases and also other diseases so that people can live longer healthy lives.= :technology:
** 微恙 =trifling ailment=
** 以肉奶为主的饮食习惯会引发各种慢性病和生理失调 =Meat and dairy centred diets are linked to many types of cancers, as well as chronic diseases such as heart ailments, diabetes, obesity, gallbladder diseases, hypertension, and more deadly diseases and psychological disorder.=
** 充分意识到健康重要性,城市居民喜欢有氧运动 =Fully aware of the importance of health, many city dwellers adore aerobic exercise.=
** 要长寿建议养成健康饮食和锻炼习惯 =To enjoy a longer lifespan, it is advisable for us adopt and maintain healthy patterns of diet and exercise.=
** 压力扰乱免疫系统 =pressure disorder our immune system=              :work:
** 白领调整生活方式保持健康 =White-collar workers should adjust their lifestyle in order to stay healthy.= :work:
*                                                                    :ethics:
** 危害社会伦理观 =harm the ethical value of the society=           :society:
** 一些人认为禁止克隆违反宪法,会剥夺生育权和限制科学自由 =Some people think that a ban on cloning may be unconstitutional and would deprive people of the right to reproduce and restrict the freedom of scientist.= :spell: :technology:
** 计划生育无可厚非 =China's family planning policy is above/beyond reproach.=
** 科学家谴责克隆人因为有悖伦理道德 =Many scientists condemn cloning human beings for it is morally and ethically wrong.= :technology:
** 正反意见抵消 =The pros and cons cancel out.=
** 令人震惊,无法容忍 =outrageous and intolerable=
** 受责任心,道德约束或至少法律的制约 =Manufactures should be subject to the sense of responsibility, moral obligation or at least the law.= :spell:
** 随着第一只克隆羊的出现人类克隆违法自然的讨论加剧 =The discussion on whether the human race can go against nature by cloning themselves has heated with the advent of the first cloned sheep Dolly.= :technology:
** 废除死刑的争论 =There arises a heated debate on whether capital punishment should be abolished.=
** 在我背后说闲话让人恼火 =It vexed me to think of others gossiping behind my back.=
** 光阴一去不复返 =Nothing can compensate for the loss of time.=
** 为暴行赎罪 =The invaders must atone for atrocities they committed.=
** 运动员服用禁药并不少见 =Abuse of performance-enhancing drugs is not uncommon among athletes.= :spell:
** 不充分讨论利弊无法评估毒品合法化必要性 =It's hard to make assessment on the necessity of drug legalisation if merits and demerits are not fully discussed.= :crime:
** 怀疑论者将其归因于生活的不公 =A sceptic may put it down to life inequalities.=
** 轻率的，无知的，懒惰的，只看事情表面的结果而不是事情本身，就会归功于运气、命运、和巧合 =The thoughtless, the ignorant, and the indolent, seeing only the apparent effects of things and not the things themselves, talk of luck, of fortune, and chance.=
*                                                                      :work:
** 远程工作环境没有休息室饮水机和同事间谈话让我们分心 =There is no break-room, no water fountain and no peer discussions to keep us away from our work in the telecommunication environment.=
** 应对压力 =handle stress=
** 跳槽仍被视为是在职业路途上实现更高目标的关键之一 =Job transition is still viewed as one of the keys to fulfill highter goal in the professional path.=
** 破坏言论自由的氛围 =damage the atmosphere of free expression of ideas=
** 他不顾一切困难 =He was going ahead defying all difficulties.=
** 成功与否要看努力和能力 =Success depends on your effort and ability.=
** 开放办公环境使员工自由交流 =An open office environment makes workers communicate directly and freely.=
** 不接触同事不了解公司状况阻碍职业发展 =The lack of daily contact with coworkers could take us out of the loop relative to what is going on within the company. This lack of inside knowledge could affect our advancement within the company.=
** 人际关系紧张,工作压力大,竞争激烈导致白领精神崩溃 =Tense human relationships, heavy pressure from work and life and fierce competition contribute to many white-collar workers' nervous breakdown.= :spell: :health:
** 勤劳简朴适应于一切事业 =The principle of diligence and frugality applies to all undertakings.=
** 过去几年在跨国公司积累丰富经验 =In the past few year, I've been working for a famous multinational and therefor attained fair knowledge and rich experience in this field.=
** 适应规范 =adapt to norms=
** 能够适应世界变化对个人很重要 =Learning to adapt to the changing world is of great significance to a person.= :spell:
** 嘴上说说却从不付诸行动 =He always purport to do something but never act out.=
** 竞争激烈白领自杀数上升 =The number of white-collar workers who commit suicide increases with the increasingly intensive social competition.= :health:
*                                                                    :family:
** 他可能缺少与家人感情交流 =He may lack adequate exchange of feelings with his faminly members.=
** 夫妻间感性和理性需求与维持婚姻本身相比是次要的 =The emotional and intellectual needs of spouses are secondary to the survival of the marriage itself.=
** 宣布你们结为夫妻 =I now pronounce you husband and wife.= :spell:
** 这个缺点抵消了本来还算开明的态度 =The weakness negates his otherwise progressive attitude.=
** 成功的婚姻归因于魅力,奉献和耐心 =A successful marriage can be ascribed to attraction, devotion and patience.=
*                                                                      :life:
** 靠不道德收入生活 =live off immortal earnings=                      :crime:
** 他靠父亲生活 =He had lived off his father all his life.=
** 退休安度晚年 =live out one's life in retirement=
** 过积极向上的生活 =lead a productive life=
** 过体面的生活 =lead a decent life=
** 过懒散的生活 =lead an indolent life=
** 网络成瘾是耗时的爱好不应鼓励 =Addiction to the Internet is a time-consuming hobby that should be discouraged.= :spell: :education:technology:
** 业余爱好 =Leisure time pursuits influence one's thought-habit.=
** 期待广州之行愉快 =We anticipate great pleasure from our visit to Guangzhou.=
** 一部充满恐怖暴力但却引人入胜的电影 =a frighteningly violent yet compelling film=
*                                                                    :gender:
** 官方数据显示越来越多女性参与暴力犯罪 =Official statistics show that a growing number of females are involved in violent crimes.=
** 有证据表明越来越多女性参与暴力犯罪如谋杀绑架抢劫 =There is evidence that a growing number of females are engaged in violent crimes such as murder, kidnap and armed robbery.= :structure:crime:spell:
** 应鼓励女性追求事业施展才华 =Females should be encouraged to pursuit their careers so that they can exhibit their versatile talents.=
** 要求女性做全职主妇是严重歧视妇女,这种建议荒唐不切实际 =Asking females to be full-time housewives severely discriminates against women and the proposal is absurd and impractical.= :spell:
** 体力劳动几乎全部有男性完成 =Manual labour has been performed almost exclusively by men.=
** 最佳生育年龄 =prime child-bearing age=                              :work:
** 职业女性很难平衡工作和家庭 =Many career women find it really hard to balance work and family life.=
*                                                                    :animal:
** 克隆技术可用于增加濒危物种数量保护他们免于完全灭绝.这将有助于维持地球自然平衡和持续生命循环 =Cloning could be used to increase the population of endangered species of animals and thus save them from total extinction. This would help maintain a natural balance on the earth and have a continuous natural life cycle.= :technology:
** 已证实宠物可能导致流行病爆发 =It has long been established that pets may give rise to the outbreak of epidemics.= :health:
** 生物多样性要不惜代价保护同时采取措施保证避免更多种类灭绝 =Biodiversity must be preserved at all costs and measures must be taken to ensure more species do not become extinct.= :spell:
** 是否该拿动物做实验动物保护者不同意科学家 =Animal-rights activists disagree with scientists over whether humans are entitled to conduct experiments on animals.= :ethics:
** 过多旅游可能破坏野生动物栖息地 =Too much tourism may destroy the natural habitats of wildlife.= :culture:
** 熊猫和秃鹰被列为濒危物种 =Pandas and bald eagles are classified as endangered species.= :spell:
** 邻居家养宠物的人们总是埋怨睡觉被吵醒 =People whose neighbours have pets always complain that their sleep is interrupted at midnight by the pets' noises.= :family:
** 与宠物的积极关系有助于建立与他人的信任 =Positive relationships with pets can be an aid in the development of trusting relationships with others.=
** 中国越来越多人加入到保护珍稀动物的运动 =More and more people in China have entered the campaign to save rare animals from extinction.=
** 动物保护人士反对为了人类利益虐待动物 =Animal activists assert their opposition to the fact that animals are abused for man's interests.=
** 虐待动物不道德 =It's unethical and barbaric to abuse animals.=    :ethics:
*                                                                :technology:
** 电子书技术符合网络社会的需求和发展 =E-book technology meets the requirements and development of the network society.= :spell:
** 现代技术让做家务更简单 =Modern technologies facilitate domestic work.=
** 计算机技术从未像现在这样用途广泛 =Never before has computing been so versatile.=
** 保守人士不接受新思想新技术而坚持传统 =Some conservative people refuse to embrace new ideas and technologies and they adhere to old traditions and practices.=
** 智能机器广泛应用于制造业有助于降低成本 =Intelligent machines have their wide application in the manufacturing industry for they can help diminish the cost of production.=
** 不可否认电脑广泛使用对我们生活造成深远影响,成为我们不可或缺的一部分 =There is no denying that the wide application of computers has produced far-reaching influence on our daily lives and become an indispensable part of us.= :spell: :structure:
** 通过电脑互联网交互和电视会议,信息能容易地传给老师和学生 =Information can be delivered easily to teachers and students through computers, interactive capabilities of networks and video conferencing.= :education:
** 在审查互联网之前要先定义什么是色情,是否包含书籍杂志图片还是单指互联网 =Before censoring the Internet, we will have to define what is meant by "pornography" - does the term include books, magazines, pictures or just the Internet.= :spell:
** 工序由电脑控制 =The process are all electronically controlled.= :spell:
** 因特网是传播信息的便捷途径 =The Internet is a convenient way to convey information.= :spell:
** 依靠无线技术发达国家实现远程教育 =Based on wireless technology, developed countries have realised the breakthrough of providing long distance education for children in remote areas.= :education:
** 互联网加速信息传播 =The advent of the Internet has accelerated the flow of information.=
** 宇航员圆满完成任务 =The astronaut has accomplished the mission successfully.=
** 成年人需要学习电脑
 =With the application of computers, many adults feel the pressing need of acquiring computer literacy.=
*                                                                   :culture:
** 传统绘画占掉美术馆里大部分墙面 =Traditional paintings occupy most of the wall-space in the gallery.=
** 游客涌入影响本地安宁生活 =The influx of tourists interferes with the locals' quiet lift.=
** 部落压力山大来自经济社会政治,要放弃自己语言,接受大部落文化 =These tribes experienced intense pressure - economic, social and political - to give up their own cultures, including their languages, to embrace those of the major tribes.=
** 旅游业触及世界边远地区不可避免影响当地文化 =As tourism expands and reaches the remote corner of the earth, its impact on local culture is inevitable.= :spell:
** 尽管美术馆博物馆不创造利润,但丰富人们精神生活 =Although museums and galleries may not create commercial profit, they enrich people's spiritual life.=
** 人们对旅游增加外汇的作用表示怀疑 =Tourism's role in increasing foreign currency revenue has been doubted.= :structure:spell:
** 很少有人反对旅行开阔视野 =Few would dispute that travel broadens the mind.= :structure:
** 旅游有助于亲身体验,加深理解,鼓励使用文化资源 =Travelling helps to promotes an authentic experience, deepen understanding, and courage use of cultural resources for residents and visitors alike.=
** 人们年轻时开放年纪大后保守 =People tend to be more liberal when they are young and become more conservative as they get older.=
** 发展得当的话旅游业与保护古建筑不矛盾 =Carried out in the right way, tourism may not conflict with the conservation of historic buildings.=
** 文化遗产属于全人类 =Cultural heritage belongs to all human beings.=
** 封建迷信尽早废除,毒害人心 =The abolishment of superstitious practices and customs should be carried out as soon as possible since they may poison people's mind.= :spell:
** 图书馆丰富的历史文化书籍能让市民了解国家的过去 =The abundance of historical and cultural books in libraries enables citizens to have an understanding of the countries' past.=
** 市民免费使用图书馆获得信息 =Citizens should have free access to the library so that they may get contact with the latest information.=
** 奥运会开幕被用于宣传 =The opening ceremonies of the Olympic Games are now used to publicise the host countries' accomplishment and reveal the countries' connotation.= :spell:
** 老房子有魅力 =This old building has a lot of atmosphere.=
** 市政府应立项资助传统艺术家以弘扬独特本土文化 =The municipal government should approve a scheme which aims to subsidize traditional artists so as to carry forward our unique indigenous culture.= :spell:
** 政府应筹划项目以挽救濒危语言 =The government should arrange for special programmes to save endangered languages.= :society:
** 语言学家有责任保护濒危语言 =Linguists assume new duties of storing as much information as possible about extinct languages.=
** 鼓励原住民坚持传统 =Aboriginals should be encouraged to adhere to their cultural traditions.=
** 我们永远不能放弃民族特性 =We shall never abandon our national identity.=
** 保护文化遗产,去糟取精 =The best way to protect our cultural heritage is to absorb the essence and discard the dregs.=
** 求同存异 =to seek common ground while reserving differences=
** 这篇文章除了长之外没什么不好 =The article is long, but not otherwise blameworthy.=
** 移民融入社区 =Immigrants try to assimilate into the community.=
** 欣赏不同文化 =appreciate a difference culture=
** 开阔视野 =broaden one's horizon=
** 扩大知识面 =broaden one's scope of knowledge=
** 开阔眼界 =broaden one's vision=
** 旅行开阔心智 =Traveling broadens the mind.= :spell:
*                                                                     :media:
** 代言系列美容产品 =The movie star endorses a line of cosmetic products.=
*                                                                    :sports:
** 世界杯等赛事缓和了国际关系紧张 =International sports events like the World Cup ease tensions between nations.= :international:
** 近来出现激烈辩论关于是否帮助充实危险运动的人 =Recently, there has been a heated debate over whether we should offer assistance to those who engaged in dangerous sports when they encounter life threatening situations.= :ethics:structure:
*                                                                   :society:
** 那里的人度过了饥荒 =People there lived through the famine.=
** 减税政策必然导致公共支出减少 =Policies of tax reduction must leads to reduced public expenditure.=
** 改善当地人福利 =improve the well-being of local inhabitants=
** 实施更严格的控制 =impose more rigid control over=
** 给...增加负担 =impose a strain on=
** 政府应该采取更严格的交通法规并且对违规者实施更严厉的惩罚 =The government should issue stricter traffic laws and regulations, and impose more severe and harsher penalties on violators.= :spell:
** 国家通过旅游业创造就业机会增加收入和税收 =Countries generates job opportunities, increase income and tax revenue by tourism.=
** 政府鼓励艺术家表达思想为各年龄人们创造更多艺术品 =The government encourages artists to express themselves and create more artistic works for people of all ages.=
** 申报个人收入 =declare one's income=
** 老人喜欢养老院因为服务一流和结识朋友 =Some old people enjoy living in the nursing home because the nursing home not only provides first-rate service but also creates opportunities for them to make new friends.= :spell:
** 城乡差距因素之一是资源分配不均 =One factor leading to the gap between urban and rural areas is that social resources are unevenly distributed.= :structure:
** 没有公司更够承担中国为敌的后果 =No company can afford to antagonize China.=
** 股票价格剧烈变动 =The stock price altered sharply.=
** 汽车自行车停路边严重阻碍交通 =Cars and bikes parked along the streets block the flow of traffic, sometimes leading to serious traffic congestion.= :spell:
** 街道难容私家车 =The narrow streets can hardly accommodate the increasingly large number of private cars.=
** 控制平民获得武器途径 =control the flow of guns to general populace=
** 经济保持缓慢发展 =The economy remains sluggish.=
** 负责人的政府应该尽力帮助弱势群体摆脱贫困消除疾病 =A responsible government should always endeavour to help the disadvantaged to tackle poverty, conquer diseases and eliminate illiteracy.= :spell:
** 把避税和逃税分开是很重要的 =It's important to distinguish between tax avoidance and tax evasion.=
** 民主要求公民智慧和远见,所以必须鼓励和支持教育,推进艺术和人文 =Democracy demands wisdom and vision in its citizens. It must therefor foster and support a form of education, and access to the arts and humanities.= :structure:
** 过度消费导致严重赤字 =Excessive consumption resulted in heavy trade deficit.=
** 分配给公共教育的资金不该被滥用 =Funds allocated for public education should not be misused.= :education:
** 为无家可归者提供食宿 =afford food and beds for the homeless=      :ethics:
** 有争议的政策引来国际批评 =The controversial policy have attracted international censure.=
** 政府需要关注老年人需求多建养老院 =The government should attend to the needs of the elderly and more nursing homes should be established.=
** 对零售商强制罚款 =Fines are imposed on retailers.=
** 解决办法就在政府手中 =The remedy lies in the hands of the government.=
** 卫生部门解决城市垃圾问题 =The health authority should take proper measures to deal with the increasingly serious rubbish problem in urban areas.= :health:
*                                                                     :crime:
** 降低犯罪率 =lower the crime rate=
** 这项法律严禁种族和性别歧视 =The law strictly forbids racial and sexual discrimination.=
** 在本文我将探讨为什么青少年吸毒 =In this essay, I intend to explore why teenagers like drugs.= :education:structure:
** 他们成功逃出敌手 =They managed to escape the clutches/grip of the enemy soldiers.= :spell:
** 事实上非法赌博庄家每年赚几十亿美元 =The fact is that, illegal gambling promoters earn over several billion dollars a year.= :structure:spell:
** 反对者称赌博促使犯罪降低社会幸福水平 =Opponents argue that gambling increases crime rate and decreases the general welfare of the society.= :spell: :structure:
** 持续暴力使谈判进程减速 =Continuing violence will retard the negotiations over the country's future.=
** 他拒绝透露关于那个人的任何消息 =He refused to divulge any information related to/regarding/concerning/involving the man's whereabouts.=
** 谴责侵略,请求宽容 =denounce the invasion and plead for tolerance= :spell:
** 青少年犯罪值得关注 =Juvenile delinquency is one of the several matters that claims the public attention.= :education:
** 被胁迫认罪 =Sometimes one might be coerced into pleading guilty.=
** 青少年吸毒归咎于无知和好奇 =We often attribute youth drug abuse to ignorance and curiosity.= :education:
** 使用某些化学品违法 =The use of certain chemicals has now been declared illegal.= :spell:
*                                                             :international:
** 目前双方都遵守停火协议 =So far the ceasefire has been observed by both sides.=
** 当局无法确保联合国调查员安全 =The authorities could not guarantee the safety of the UN observers.= :spell:
** 根据协议所有贸易壁垒都将被消除 =Under the agreement, all trade barriers will be eliminated.=
** 发展中国家与发达国家竞争世界市场 =Developing countries have to compete with developed countries for the world market.=
*                                                                    :letter:
** 许多菜因加入新鲜香草而大有改善 =Many dishes are greatly improved by adding fresh herbs.=
** 作者把内容处理得简明扼要 =The writer handles the matter briefly and concisely.=
** 他的个性对委员会其他成员有决定性影响 =His personality dominated the other members of the committee.= :spell:
** 这些建议值得认真考虑 =These proposals deserve serious consideration.=
** 感谢你发的培训小册子 =I shall appreciate it if you could send me some relevant booklets regarding the training programme.=
** 收费后维多利亚艾伯特美术馆参观人数下降了15% =Visitors to the Victoria and Albert Museum in London declined by 15% after it started charging for admission.=
*                                                                     :graph:
** 该图展示了两种房屋的内部结构 =The diagram demonstrates the internal structure of two types of houses.= :spell:
*                                                                 :structure:
** generate a fiece argument
** opponents/proponents argue that...
** on the grounds of
** with roots in
*                                                                     :bonus:
** sue complain grumble whine mutter murmur
** is secondary to
** but otherwise
** not uncommon
** ineffective half-measures
** if it were not for
** quite the opposite in fact
v
