* Sleeping on the Job
http://www.mensfitness.com/nutrition/sleeping-on-the-job-should-you-nap-at-work
Sleeping on the job boosts productivity.
Siestas company policy.
Daytime drowsiness can affect mood, productivity, and creativity, but a brief nap may provide greater alertness for several hours to help improve attention, concentration and accuracy.
Napping perk.
Cardiovascular disease and depression.
Sleep-deprived workers.
Stretching out.
Dozing in your cubicle.
Fool passersby into thinking you’re hard at work.
Drool on your report.
Our inner body clocks start to make us feel drowsy around siesta time—or somewhere between 1 and 4 p.m.—so aim to fit in a nap during these hours.
Make quick naps a daily ritual.
Get into the sleep mindset.
Doze off.
Snooze.
Catnaps.
Avoid snoozing too long and waking up groggy.
Longer naps have the downside of greater sleep inertia.
Set your cell phone or another device to go off after about 15 minutes.
You’ll feel recharged enough to tackle your afternoon agenda and still hit the gym after work.
* My Thodio Review
http://store.thodio.com/
"Wow! Not sure where to start!! I’ve been working with Thomas Spaans in building my XC’s for quite a while!!! I knew the products were going to be good but had no idea what I was in for…(I’ll try and make this review short…lol ….I have had an obsession with home audio equipment since I can recall. I used to work for a high end California based retailer who placed a few of their stores out here in Florida. Nevertheless, I got to sell some incredibly high end stuff which allowed me to consume not just my clienteles genre of music styles and knowledge but of course their discriminating taste in wanting the best of the best when it came to Home Audio.

I used to throw pool parties with my friends and was always in charge of bringing the music. I owned a Bose dock, which was ok for the time being, but it just did not do it for me. It lacked mids, some highs ….just overall transparency.. I decided to take a journey in search of something portable that would not only satisfy my crazy audio needs (quality, power…materials…you name it) but something that would also wow people as far as looks and everything above. That’s when I came across Thodio’s page. It was like love at first site  I came in contact with Thomas a few days later and the process of building my two XC’s were a go. What I love about Thodio as a company is the patience they had with me throughout the whole entire process….You want to talk about customization! I pretty much nailed it with everything I had him do to mine (thanks again Thomas)

When it came to customization, I made sure to not miss or overlook any needed specifics or details, neither did Thodio, they actually helped me in ways to improve on the specifics that I wanted. ..just wow!!!! I have never worked with a company that was so personable and eager to meet all of my expectations! Lets now get to the good part!!!! When I got my XC’s delivered…I think I called in to work sick that day from all of the excitement! Opening up the package on these things was just stunning!! I Could not believe the type of craftsmanship that were put into my XC’s!!! The sound was just breath taking!!!! I think my Bose dock started crying from what was being delivered out of the XC!!! (Needless to say..the Bose got tossed  The sounds were warm, vibrant and made me feel as if I was right on stage with the artist. The TK2050 amp is no joke folks!!! When it comes to power, the XC is just a monster!! It craves power like no other!!! This isn’t the power most people are used to from the everyday and ordinary plastic boom boxes you find out on the shelf. The power is INCREDIBLY STRONG, in combination with quality sounds that are just LUSH!!! No distortion whatsoever!!! It just makes you want to rehear all of your old tracks, because I guarantee you might have missed something=)

These things are not cheap but I must say, for what its worth..Im now a Thodio Customer for life! Going to order my third XC from him in the near future (pretty soon actually  ..Thomas just wanted to say thanks for all your patience, hard work and dedication!! Thanks for making Thodio what it is today!!! We’ll keep in touch soon."

-George Barrera (Orlando, FL)
* TODO
idiomatic, harvest, charisma
